### PR TITLE
fix: Localisation-matching algorithm missing some edgecase

### LINKED ISSUE #4690: Locale detection ignores English language since v1.23.12
### 📑 I have found these related issues/pull requests

#4244 (see review for exact cause)

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

English language is now silently skipped, even if browser indicates that it is of higher priority. Instead, the next highest priority language is used.

### 👟 Reproduction steps

```
navigator.languages => ['en-US', 'en', 'pl', 'ja']
```

```
Accept-Language: en-US,en;q=0.9,pl;q=0.8,ja;q=0.7
```

chrome_2024-04-19_00-25-01

### 👀 Expected behavior

Interface and status page is displayed in English

### 😓 Actual Behavior

Interface and status page is displayed in Polish

### 🐻 Uptime-Kuma Version

1.23.12

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Chromium124.0.6367.61

### 🖥️ Deployment Environment

- Runtime: Docker version 25.0.4, build 1a576c5
- Database: sqlite/embedded
- Filesystem used to store the database on: ext4 via docker volume

### 📝 Relevant log output

_No response_

### LINKED ISSUE #4691: Setting English as language in settings does not persist
### 📑 I have found these related issues/pull requests

#4244

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Setting language in settings to English does not persist between reloads of page because internally, Uptime Kuma does not recognize that language as valid.

### 👟 Reproduction steps

1. Ensure auto-detected language is something else than English
2. Go to Settings -> Appearance -> Language and select English
3. Refresh page

### 👀 Expected behavior

Language settings is persisted according to user preference

### 😓 Actual Behavior

Language is reverted to auto-detected one based on locale

### 🐻 Uptime-Kuma Version

1.23.12

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Chromium124.0.6367.61

### 🖥️ Deployment Environment

- Runtime: Docker version 25.0.4, build 1a576c5
- Database: sqlite/embedded
- Filesystem used to store the database on: ext4 via docker volume

### 📝 Relevant log output

_No response_

### LINKED ISSUE #4697: Issue with detecting language with 3 letter code
### 📑 I have found these related issues/pull requests

I don't seem to find any related issue.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When the system or web browser is set to a language with three letters (e.g. Filipino, which is `fil`), it only parses the first two (`fi`) and would automatically assume it's that language (which is Finnish in this case) and chooses that one instead. Since there is no Filipino translation yet, I would expect it to fall back to English, but not in this case because of the issue.

Screenshot:
image

### 👟 Reproduction steps

As far as I know, only Chromium has the option for the Filipino language, so use that instead if you can

1. Set the preferred language to Filipino on `chrome://settings/languages`, make sure its at the very top.
2. Visit any Uptime Kuma instance, like https://status.codeberg.eu or the demo version provided in the README

### 👀 Expected behavior

Since there is no Filipino translation yet, it should fall back to English

### 😓 Actual Behavior

Uses the Finnish language instead

### 🐻 Uptime-Kuma Version

1.23.12

### 💻 Operating System and Arch

Arch Linux

### 🌐 Browser

Chromium 122.0.6261.111

### 🖥️ Deployment Environment

Not applicable

### 📝 Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by CommanderStorm**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Resolves #4691
Resolves #4690
Resolves #4697

There were these minor bugs in the new language selection mechanism introduced in `1.23.12`:
- we only fall back to the generic locale (for `en-US` this would be `en`) for the first entry of the languages
- We never match `en` if other (less prefered) alternatives exist in the users preferences, as this is only in the messages and not in the `languageList`.
- We assumed that the generic locales are only 2 characters, not 3

Our testcases missed this edgecase

thanks @CirnoT for the bug report

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [x] My code needed automated testing. I have added them (this is optional task)

### CODE REVIEW

**Comment by Zaid-maker** [comment]
When their will be 1.23.X release?

File: src/i18n.js [hunk 1]
```diff
@@ -63,8 +63,11 @@ const rtlLangs = [ "fa", "ar-SY", "ur" ];
  * @returns {string} the locale that should be displayed
  */
 export function currentLocale() {
-    const potentialLocales = [ localStorage.locale, navigator.language, navigator.language.substring(0, 2), ...navigator.languages ];
-    const availableLocales = potentialLocales.filter(l => languageList[l]);
+    const potentialLocales = [ localStorage.locale, navigator.language, ...navigator.languages ];
+    const availableLocales = potentialLocales
+        .filter(l => !!l)
+        .map(l => l.split("-")[0] in messages ? l.split("-")[0] : l)
+        .filter(l => l in messages);
```
Comment (louislam) [inline src/i18n.js:70]: Since it is getting more conditions now, is it able to break them down into more traditional programming `for-loop` and `if-else`? Because I am a bit struggling to understand why those bugs is happening.

Also it didn't utilize `languageList` anymore here, make me wondering if it is really ok.

File: src/i18n.js [hunk 2]
```diff
@@ -63,9 +63,22 @@ const rtlLangs = [ "fa", "ar-SY", "ur" ];
...
+        // localstorage might not have a value or there might not be a language in `navigator.language`
+        if (!locale) {
+            continue
+        }
+        if (locale in messages) {
+            return locale;
+        }
+        // some locales are further specified such as "en-US".
+        // If we only have a generic locale for this, we can use it too
+        const genericLocale = l.split("-")[0];
```
Comment (CommanderStorm) [inline src/i18n.js:76]: minor typo

```suggestion
        const genericLocale = locale.split("-")[0];
```

File: src/i18n.js (hunk 1 above)
Comment (CommanderStorm) [reply src/i18n.js]: I have refactored this to a for-loop.
not checking against `languageList` is because "en" is sort of a magic value amongst all the languages => is only in the `messages` and not in the `languageList`

File: src/i18n.js [hunk 3]
```diff
@@ -63,9 +63,22 @@ const rtlLangs = [ "fa", "ar-SY", "ur" ];
  * @returns {string} the locale that should be displayed
  */
 export function currentLocale() {
-    const potentialLocales = [ localStorage.locale, navigator.language, navigator.language.substring(0, 2), ...navigator.languages ];
-    const availableLocales = potentialLocales.filter(l => languageList[l]);
-    return availableLocales[0] || "en";
+    for (const locale of [ localStorage.locale, navigator.language, ...navigator.languages ]) {
+        // localstorage might not have a value or there might not be a language in `navigator.language`
+        if (!locale) {
+            continue
```
Comment (CommanderStorm) [inline src/i18n.js:69]: Formatting fix
```suggestion
            continue;
```

File: src/i18n.js (hunk 1 above)
Comment (louislam) [reply src/i18n.js]: Thanks, I got it now. I am really bad at reading/tracing functional programming style code.🤣

File: test/cypress/unit/i18n.spec.js [hunk 4]
```diff
@@ -3,46 +3,62 @@ import { currentLocale } from "../../../src/i18n";
...
+        setLanguages(['ja-ZZ']);
         expect(currentLocale()).equal("ja");
 
-        setLanguage('zz-ZZ');
+        setLanguages(['zz-ZZ']);
         expect(currentLocale()).equal("en");
 
-        setLanguage('zz-ZZ');
+        setLanguages(['zz-ZZ']);
         expect(currentLocale()).equal("en");
```
Comment (Saibamen) [inline test/cypress/unit/i18n.spec.js:38]: This is the same test case as in line 35
