### PR TITLE
Fix for issue in logs

### LINKED ISSUE #1024: error in logs: "TypeError: Cannot read property 'daysRemaining' of null"
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I can see this error in my logs from uptime-kuma every few minutes:

TypeError: Cannot read property 'daysRemaining' of null
at Prometheus.update (/app/server/prometheus.js:63:91)
at beat (/app/server/model/monitor.js:396:24)
at async Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:419:17)

FYI I'm not using Prometheus, just the base docker image with just a few http monitors configured, no special settings or anything

### 👟 Reproduction steps

deploy uptime kuma, add a monitor, wait and check the container logs

### 👀 Expected behavior

we should not have this error every few minutes in the logs

### 😓 Actual Behavior

I can see this error in my logs from uptime-kuma every few minutes:

TypeError: Cannot read property 'daysRemaining' of null
at Prometheus.update (/app/server/prometheus.js:63:91)
at beat (/app/server/model/monitor.js:396:24)
at async Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:419:17)

### 🐻 Uptime-Kuma Version

1.11.1

### 💻 Operating System and Arch

Ubuntu 20.04 - x64

### 🌐 Browser

Chrome

### 🐋 Docker Version

_No response_

### 🟩 NodeJS Version

_No response_

### 📝 Relevant log output

```shell
TypeError: Cannot read property 'daysRemaining' of null
at Prometheus.update (/app/server/prometheus.js:63:91)
at beat (/app/server/model/monitor.js:396:24)
at async Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:419:17)
```

### PR DESCRIPTION
**Pull request by jbenguira**
This fix address the issue described here: https://github.com/louislam/uptime-kuma/issues/1024

# Description

I can see this error in my logs from uptime-kuma every minute:

TypeError: Cannot read property 'daysRemaining' of null
at Prometheus.update (/app/server/prometheus.js:63:91)
at beat (/app/server/model/monitor.js:396:24)
at async Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:419:17)

FYI I'm not using Prometheus, just the base docker image with just a few http monitors configured, no special settings or anything

Fixes #1024

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code and tested it
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings

### CODE REVIEW

File: server/prometheus.js [hunk 1]
```diff
@@ -60,7 +60,9 @@ class Prometheus {
             }
 
             try {
-                monitor_cert_days_remaining.set(this.monitorLabelValues, tlsInfo.certInfo.daysRemaining);
+                if ( tlsInfo.certInfo != null ){
```
Comment (Saibamen) [inline server/prometheus.js:63]:
```suggestion
                if (tlsInfo.certInfo != null) {
```

**Review by Saibamen — CHANGES_REQUESTED** [review]

**Comment by Saibamen** [comment]
Please update `Fixes #(issue)` in first post to connect it with #1024

**Comment by jbenguira** [comment]
> Please update `Fixes #(issue)` in first post to connect it with #1024

done

**Review by Saibamen — APPROVED** [review]

**Comment by jbenguira** [comment]
> Still not linked yet: image
> 
> ```
> Fixes #(issue)
> #1024
> ```
> 
> should be replaced to:
> 
> ```
> Fixes #1024
> ```

fixed now
