### PR TITLE
fix: expand/collapse all groups now works with nested groups

### LINKED ISSUE #6788: Expand All Groups doesn't expand all groups
### 📑 I have found these related issues/pull requests

None

### 🛡️ Security Policy

- [x] I have read and agree to Uptime Kuma's [Security Policy](https://github.com/louislam/uptime-kuma/security/policy).

### 📝 Description

Trying the new Expand All Groups button. It collapses all groups ok, but doesn't expand them all. It seems to expand the top-level groups, but in 2nd level it only seems to expand some groups, not all and, for me, hasn't expanded any 3rd level groups.

### 👟 Reproduction steps

Setup with multiple groups, and groups within groups. Collapse all groups - works fine. Expand all groups - doesn't expand everything.

### 👀 Expected behavior

Should expand all groups (for all shown monitors).

### 😓 Actual Behavior

Doesn't expand all groups.

### 🐻 Uptime-Kuma Version

2.1.0-beta.3 Frontend Version: 2.1.0-beta.3

### 💻 Operating System and Arch

Docker on Ubuntu 24.04.3 lts

### 🌐 Browser

Edge

### 🖥️ Deployment Environment

- **Runtime Environment**:
  - Docker: Version 29.1.5
- **Uptime Kuma Setup**:
  - Number of monitors: 257 active, 87 paused.

### 📝 Relevant log output

```bash session
No log messages produced.
```

### PR DESCRIPTION
**Pull request by kurama**
# Summary

In this pull request, the following changes are made:

- The expand/collapse all groups button now properly handle nested group hierarchies at any depth level, instead of only working with root-level groups
- When collapsing all groups while viewing a nested group, the user is automatically navigated to the root parent group for a better UX
- The `groupMonitors` computed property was updated to include all groups with children, regardless of their nesting level, by removing the `parent === null` filter
- Added navigation logic that traverses up the group hierarchy to find the root parent and redirecfts the user there when collapsing from a nested view

I tested this by reproducing the scenario shown in the video from the issue, and the expand/collapse functionality now works correctly with nested groups at all levels.

Please test on your side and tell me if and don't hesitate to tell me if I've forgotten anything.

- Relates to #6788
- Resolves #6788

<details>
<summary>Please follow this checklist to avoid unnecessary back and forth (click to expand)</summary>

- [ ] ⚠️ If there are Breaking change (a fix or feature that alters existing functionality in a way that could cause issues) I have called them out
- [ ] 🧠 I have disclosed any use of LLMs/AI in this contribution and reviewed all generated content.
      I understand that I am responsible for and able to explain every line of code I submit.
- [ ] 🔍 Any UI changes adhere to visual style of this project.
- [ ] 🛠️ I have self-reviewed and self-tested my code to ensure it works as expected.
- [ ] 📝 I have commented my code, especially in hard-to-understand areas (e.g., using JSDoc for methods).
- [ ] 🤖 I added or updated automated tests where appropriate.
- [ ] 📄 Documentation updates are included (if applicable).
- [ ] 🧰 Dependency updates are listed and explained.
- [ ] ⚠️ CI passes and is green.

</details>

## Screenshots for Visual Changes

- **UI Modifications**: Highlight any changes made to the user interface.
- **Before & After**: Include screenshots or comparisons (if applicable).

| Event              | Before                | After                |
| ------------------ | --------------------- | -------------------- |
| `UP`               | Before | After |
| `DOWN`             | Before | After |
| Certificate-expiry | Before | After |
| Testing            | Before | After |

### CODE REVIEW

**Comment by kurama** [comment]
Added infinite loop protection with `MAX_TRAVERSEL_STEP = 1000` as GitHub Copilot mentionned. Not sure what a realistic maximum nesting depth would be ?

File: src/components/MonitorList.vue [hunk 1]
```diff
@@ -360,6 +359,41 @@ export default {
...
+                        rootParent.parent !== null &&
+                        !visited.has(rootParentId) &&
+                        safetyCounter < MAX_TRAVERSAL_STEPS
+                    ) {
+                        visited.add(rootParentId);
+                        rootParentId = rootParent.parent;
+                        rootParent = this.$root.monitorList[rootParentId];
+                        safetyCounter++;
+                    }
+
```
Comment (CommanderStorm) [inline src/components/MonitorList.vue]: If circular groups are possible (have not checked, they might), this is a bug.

Let's not add handling for potential bugs in the frontend and simplify this to your OG version of this.

Comment (kurama) [reply src/components/MonitorList.vue]: Done

**Comment by CommanderStorm** [comment]
thanks ❤️
