### PR TITLE
fix: Expand the logging around AggregateError

### LINKED ISSUE #6482: AggregateError does not have good support for logging which n errors occurred
### 📑 I have found these related issues/pull requests

Notification is not working - Aggregation error

### 🛡️ Security Policy

- [x] I have read and agree to Uptime Kuma's [Security Policy](https://github.com/louislam/uptime-kuma/security/policy).

### 📝 Description

_No response_

### 👟 Reproduction steps

Uptime Kuma Version 2.0.2 - dockerized 
Environment: Kubernetes / Rancher RKE2 

Websocket support activated

Proxy: tried it with and without 

Reproduce: 

1. Run uptime Kuma
2. Add a new service 
3. Add a new SLACK notification 
3.01. do a manual POST Request to that slack web hook and check if it works; if yes go on
3.1 go to Slack and create new Webhook 
3.2 Copy Webhook URL to uptime Kuma Webhook URL 
4. Leave everything else out in setting up notifications 
5. Save
6. Test the notification 
7. Wait around 30 seconds 
8. See error message Aggregation Error

I have tried it with different services and I get always the same error. 

### 👀 Expected behavior

Slack notification is reached 

### 😓 Actual Behavior

Nothing - only Aggregation error 

### 🐻 Uptime-Kuma Version

2.0.2

### 💻 Operating System and Arch

Kubernetes RKE2

### 🌐 Browser

Safari / Chrome 

### 🖥️ Deployment Environment

- **Runtime Environment**:
  - Kubernetes Version: v1.33.5 +rke2r1
  - 

</details>
<details><summary>PVC</summary>

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data
  namespace: limbs
  labels:
    app: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

</details>
<details><summary>deployment</summary>

```yaml
# Uptime Kuma Deployment
# Self-hosted monitoring tool for tracking uptime and status
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: limbs
  labels:
    app: uptime-kuma
spec:
  replicas: 1 
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      # Security context for the pod
      securityContext:
        fsGroup: 1000
      
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:2.0.2
          imagePullPolicy: IfNotPresent
          
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"          
          env:
            - name: UPTIME_KUMA_PORT
              value: "3001"
            - name: NODE_ENV
              value: "production"
          
          # Volume mounts
          volumeMounts:
            - name: data
              mountPath: /app/data
          
          # Resource limits and requests
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          
          # Liveness probe - checks if the container is alive
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          
          # Readiness probe - checks if the container is ready to serve traffic
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      
      # Volumes
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: uptime-kuma-data
```

</details>
<details><summary>service</summary>
```yaml
# Uptime Kuma Service
# Exposes the Uptime Kuma application within the cluster
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: limbs
  labels:
    app: uptime-kuma
spec:
  type: ClusterIP
  selector:
    app: uptime-kuma
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: http
  sessionAffinity: ClientIP  # Important for WebSocket connections
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
```

</details>
<details><summary>ingress</summary>

```yaml
# Uptime Kuma Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma-ingress
  namespace: limbs
  labels:
    app: uptime-kuma
  annotations:
    # WebSocket support - critical for Uptime Kuma
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    
    # WebSocket specific configuration
    nginx.ingress.kubernetes.io/websocket-services: "uptime-kuma"
    
    # Body size limit
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    
    # SSL Redirect
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"

spec:
  ingressClassName: nginx
  
  rules:
    - host: status.limbs.dkfz.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma
                port:
                  number: 3001
```

</details>

### 📝 Relevant log output

```bash session
Error: Error: AggregateError 
    at Slack.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:122:15)
    at Slack.send (/app/server/notification-providers/slack.js:175:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Socket.<anonymous> (/app/server/server.js:1486:27)
```

### PR DESCRIPTION
**Pull request by AnuragEkkati**
## 📝 Summary of changes done and why they are done

When axios requests fail with an AggregateError, the error logs just show "AggregateError" which provides no useful debugging information.

## 📋 Related issues

- Relates to #6482 
- Resolves #6482

## 📄 Checklist

<details>
<summary>Please follow this checklist to avoid unnecessary back and forth (click to expand)</summary>

- [ ] ⚠️ If there are Breaking change (a fix or feature that alters existing functionality in a way that could cause issues) I have called them out
- [X] 🧠 I have disclosed any use of LLMs/AI in this contribution and reviewed all generated content.
      I understand that I am responsible for and able to explain every line of code I submit.
- [X] 🔍 My code adheres to the style guidelines of this project.
- [ ] ⚠️ My changes generate no new warnings.
- [X] 🛠️ I have reviewed and tested my code.
- [X] 📝 I have commented my code, especially in hard-to-understand areas (e.g., using JSDoc for methods).
- [X] 🤖 I added or updated automated tests where appropriate.
- [ ] 📄 Documentation updates are included (if applicable).
- [X] 🔒 I have considered potential security impacts and mitigated risks.
- [ ] 🧰 Dependency updates are listed and explained.

</details>

## AI Usage 
Cursor AI : GPT-5. Used to generate multiple testcases which can validate if existing functionality is not broken and new desired logging works as expected.

## 📷 Screenshots or Visual Changes

- **Log Modifications**: Logging around AggregateError changed

Before : 
```
Error: Error: AggregateError
    at Slack.throwGeneralAxiosError (/Users/anurag/workspace/github/uptimekuma/uptime-kuma-test/server/notification-providers/notification-provider.js:122:15)
    at Slack.send (/Users/anurag/workspace/github/uptimekuma/uptime-kuma-test/server/notification-providers/slack.js:175:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
    at async Socket.<anonymous> (/Users/anurag/workspace/github/uptimekuma/uptime-kuma-test/server/server.js:1568:27)
```

```
Error: Error: AxiosError: Request failed with status code 500 boom
    at Slack.throwGeneralAxiosError (/Users/anurag/workspace/github/uptime-kuma/server/notification-providers/notification-provider.js:122:15)
    at Slack.send (/Users/anurag/workspace/github/uptime-kuma/server/notification-providers/slack.js:175:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
    at async Socket.<anonymous> (/Users/anurag/workspace/github/uptime-kuma/server/server.js:1567:27)
```

After : 
```
Error: Request failed (code=ECONNREFUSED) - caused by: connect ECONNREFUSED ::1:9999 (code=ECONNREFUSED); connect ECONNREFUSED 127.0.0.1:9999 (code=ECONNREFUSED)
    at Slack.throwGeneralAxiosError (/Users/anurag/workspace/github/uptimekuma/uptime-kuma-agg-error/server/notification-providers/notification-provider.js:158:15)
    at Slack.send (/Users/anurag/workspace/github/uptimekuma/uptime-kuma-agg-error/server/notification-providers/slack.js:170:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Socket.<anonymous> (/Users/anurag/workspace/github/uptimekuma/uptime-kuma-agg-error/server/server.js:1564:27)
```

```
Error: Request failed with status code 500 (code=ERR_BAD_RESPONSE) (HTTP 500 Internal Server Error) boom
    at Slack.throwGeneralAxiosError (/Users/anurag/workspace/github/uptimekuma/uptime-kuma-agg-error/server/notification-providers/notification-provider.js:158:15)
    at Slack.send (/Users/anurag/workspace/github/uptimekuma/uptime-kuma-agg-error/server/notification-providers/slack.js:170:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Socket.<anonymous> (/Users/anurag/workspace/github/uptimekuma/uptime-kuma-agg-error/server/server.js:1564:27)
```

| UI                    | Before                | After                |
| ------------------ | --------------------- | -------------------- |
| `UI Message`               | Before | After |

### CODE REVIEW

File: test/backend-test/notification-providers/test-notification-provider.js [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+        assert.throws(
+            () => provider.throwGeneralAxiosError(aggErr),
+            (thrown) => {
+                assert.ok(!thrown.message.startsWith("AggregateError"));
+                assert.ok(thrown.message.includes("caused by:"));
+                assert.ok(thrown.message.includes("127.0.0.1:443"));
+                assert.ok(thrown.message.includes("::1:443"));
+                assert.ok(thrown.message.includes("code=ECONNREFUSED"));
+                return true;
+            }
```
Comment (CommanderStorm) [inline test/backend-test/notification-providers/test-notification-provider.js]: lets be more strict/easier to understand in the assertion

```suggestion
            {
                message: "AggregateError.... <- add this part"
            }
```

File: test/backend-test/notification-providers/test-notification-provider.js [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+        outerErr.cause = aggErr;
+
+        assert.throws(
+            () => provider.throwGeneralAxiosError(outerErr),
+            (thrown) => {
+                assert.ok(thrown.message.includes("caused by:"));
+                assert.ok(thrown.message.includes("ETIMEDOUT"));
+                assert.ok(thrown.message.includes("10.0.0.1:443"));
+                return true;
+            }
```
Comment (CommanderStorm) [inline test/backend-test/notification-providers/test-notification-provider.js]:
```suggestion
            {
                message: "caused by:... <- include this"
            }
```

File: test/backend-test/notification-providers/test-notification-provider.js (hunk 1 above)
Comment (AnuragEkkati) [reply test/backend-test/notification-providers/test-notification-provider.js]: Took care of the suggestion.
