### PR TITLE
Fix: [JSON-Query] Prevent parsing string-only JSON

### LINKED ISSUE #4423: Vaultwarden "/alive" endpoint
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Vaultwarden has a "/alive" endpoint that returns a string containing a single timestamp e.g. `"2024-01-25T13:57:13.532029Z"`
Using the JSON query, I can't parse this JSON, but it works just fine in https://try.jsonata.org/

### 👟 Reproduction steps

Use the HTTP - JSON query probe
Use a website that returns a single string as JSON
Try to parse the JSON (For example `($toMillis($now())-$toMillis($))<10000`

### 👀 Expected behavior

The JSON parses just fine

### 😓 Actual Behavior

The JSON isn't parsed

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Debian 12 (Proxmox LXC)

### 🌐 Browser

Firefox 122

### 🐋 Docker Version

_No response_

### 🟩 NodeJS Version

_No response_

### 📝 Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by chakflying**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

Fixes #4423

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

image

### CODE REVIEW

File: server/model/monitor.js [hunk 1]
```diff
@@ -595,7 +595,7 @@ class Monitor extends BeanModel {
                         let data = res.data;
 
                         // convert data to object
-                        if (typeof data === "string") {
+                        if (typeof data === "string" && res.headers["content-type"] !== "application/json") {
```
Comment (CommanderStorm) [inline server/model/monitor.js:598]: I think a more reliable way would be to parse and on parse error assume that it is a string.
Opinions?

Comment (CommanderStorm) [inline server/model/monitor.js:598]: I am unsure if this is logic is correct:
So if I send out `{"a":"b"}` as `application/json` it won't be parsed.

Comment (chakflying) [reply server/model/monitor.js:598]: If the response body is a valid JSON object, it would have been deserialized as a plain JavaScript object after passing through axios.

This part of code only handle edge cases where the body is not deserialized by default.

Comment (chakflying) [reply server/model/monitor.js:598]: try-catch added.
