### PR TITLE
fix: make the websocket check more resilient to status codes, add Subprotocol inputs and Timeouts

### LINKED ISSUE #6536: (2.1.0-beta.0) WebSocket upgrade check not working (?)
### ⚠️ Please verify that your question has not already been reported

- [x] I have searched the [existing issues](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue%20sort%3Acreated-desc%20) and found no similar reports.

### 🛡️ Security Policy

- [x] I have read and agree to Uptime Kuma's [Security Policy](https://github.com/louislam/uptime-kuma/security/policy).

### 📝 Describe your problem

Hi! thanks for the awesome project.

The new WebSocket Upgrade check in 2.1.0-beta.0 isn't reporting a success for a websocket URL that testing websites all report as ok. The WSS url is: wss://api.p2k.nu/ws
This is a public URL so you can try it out yourself. I'm not quite sure what's wrong, the code to initiate the WS connection seems ok. My server does send 101 Switching Protocols but that should be fine.

Thanks!

### 📝 Error Message(s) or Log

```bash session
[MONITOR] WARN: Monitor #7 'WS': Failing: 101 - OK | Interval: 60 seconds | Type: websocket-upgrade | Down Count: 0 | Resend Interval: 0
```
Which is actually an OK state.

### 🐻 Uptime-Kuma Version

2.1.0-beta.0

### 💻 Operating System and Arch

Ubuntu Server 25.04 running Uptime Kuma in Docker

### 🌐 Browser

Zen Browser (Firefox/Gecko based)

### 🖥️ Deployment Environment

- **Runtime Environment**:
  - Docker: Version 28.3.3, build 980b856
- **Database**:
  - SQLite: Embedded
- **Database Storage**:
- **Uptime Kuma Setup**:
  - Number of monitors: `4`

### PR DESCRIPTION
**Pull request by PoleTransformer**
_ℹ️ To keep reviews fast and effective, please make sure you’ve [read our pull request guidelines](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma)_

## 📝 Summary of changes done and why they are done

Removes hardcoded response codes in the WS onClose event. Enable user to choose accepted status codes 1000-4999, defaults to 1000, which is Normal Closure. Improved error handling, will attempt to print friendly message if response code is defined.

Allow input of multiple subprotocols via a comma delimited list. Not just limited to one subprotocol chosen from dynamic list. Removes this dependancy chain on IANA, so no need to keep on updating a list in the future.

Passes `Monitor.timeout` into the `handshakeTimeout` WS option. By default the WS library doesn't have a timeout. A server that never responds will just hang the monitor.

Adds more unit tests like subprotocol checking. Removes dependency on external non compliant WS server, which I cannot guarantee the uptime. Don't want to cause false positives in the CI/CD infra due to downtime. The only external test server is wss://echo.websocket.org.

## 📋 Related issues

- Resolves #6536  
- Can close #6537

## 📄 Checklist

<details>
<summary>Please follow this checklist to avoid unnecessary back and forth (click to expand)</summary>

- [X] ⚠️ If there are Breaking change (a fix or feature that alters existing functionality in a way that could cause issues) I have called them out
- [X] 🔍 My code adheres to the style guidelines of this project.
- [X] 🦿 I have indicated where (if any) I used an LLM for the contributions
- [X] ✅ I ran ESLint and other code linters for modified files.
- [X] ⚠️ My changes generate no new warnings.
- [X] 🛠️ I have reviewed and tested my code.
- [X] 📝 I have commented my code, especially in hard-to-understand areas (e.g., using JSDoc for methods).
- [X] 🤖 My code needed automated testing. I have added them (this is an optional task).
- [ ] 📄 Documentation updates are included (if applicable).
- [X] 🔒 I have considered potential security impacts and mitigated risks.
- [X] 🧰 Dependency updates are listed and explained.

</details>

### CODE REVIEW

File: server/monitor-types/websocket-upgrade.js [hunk 1]
```diff
@@ -11,43 +31,55 @@ class WebSocketMonitorType extends MonitorType {
...
      * @param {object} monitor The monitor object for input parameters.
      * @returns {[ string, int ]} Array containing a status message and response code
      */
     async attemptUpgrade(monitor) {
         return new Promise((resolve) => {
             let ws;
-            //If user selected a subprotocol, sets Sec-WebSocket-Protocol header. Subprotocol Identifier column: https://www.iana.org/assignments/websocket/websocket.xml#subprotocol-name
-            ws = monitor.wsSubprotocol === "" ? new WebSocket(monitor.url) : new WebSocket(monitor.url, monitor.wsSubprotocol);
+            // If user inputs subprotocol(s), convert to array, set Sec-WebSocket-Protocol header, timeout in ms. Subprotocol Identifier column: https://www.iana.org/assignments/websocket/websocket.xml#subprotocol-name
+            ws = !monitor.wsSubprotocol ? new WebSocket(monitor.url, { handshakeTimeout: (monitor?.timeout ?? 0) * 1000 }) : new WebSocket(monitor.url, monitor.wsSubprotocol.replace(/\s/g, "").split(","), { handshakeTimeout: (monitor?.timeout ?? 0) * 1000 });
```
Comment (CommanderStorm) [inline server/monitor-types/websocket-upgrade.js]: is 0 really a good default timeout?
How about 20s instead 😉

File: src/lang/en.json [hunk 2]
```diff
@@ -90,39 +90,9 @@
...
-    "BACnet Secure Connect Direct Connection": "BACnet Secure Connect Direct Connection",
-    "WebSocket Transport for JMAP": "WebSocket Transport for JMAP (JSON Meta Application Protocol)",
-    "ITU-T T.140 Real-Time Text": "ITU-T T.140 Real-Time Text",
-    "Done.best IoT Protocol": "Done.best IoT Protocol",
-    "Collection Update": "The Collection Update Websocket Subprotocol",
-    "Text IRC Protocol": "Text IRC Protocol",
-    "Binary IRC Protocol": "Binary IRC Protocol",
-    "Penguin Statistics Live Protocol v3": "Penguin Statistics Live Protocol v3 (Protobuf encoding)",
+    "wsSubprotocolDescription": "Enter a comma delimited list of subprotocols. For more information on subprotocols, please consult the {documentation}",
+    "wsCodeDescription": "For more information on status codes, please consult {documentation}",
```
Comment (CommanderStorm) [inline src/lang/en.json]:
```suggestion
    "wsCodeDescription": "For more information on status codes, please consult the {documentation}",
```

File: src/pages/EditMonitor.vue [hunk 3]
```diff
@@ -889,6 +824,36 @@
...
+                                        :max-height="600"
+                                        :taggable="true"
+                                    ></VueMultiselect>
+
+                                    <div class="form-text">
+                                        {{ $t("acceptedStatusCodesDescription") }}
+                                    </div>
+                                    <i18n-t tag="div" class="form-text" keypath="wsCodeDescription">
+                                        <template #documentation>
+                                            <a href="https://datatracker.ietf.org/doc/html/rfc6455#section-7.4" target="_blank" rel="noopener noreferrer">{{ 'RFC6455' }}</a>
```
Comment (CommanderStorm) [inline src/pages/EditMonitor.vue]: not qutie sure why you did it like that, but I would do it like this. 🤔


```suggestion
                                            <a href="https://datatracker.ietf.org/doc/html/rfc6455#section-7.4" target="_blank" rel="noopener noreferrer">RFC6455</a>
```

File: src/pages/EditMonitor.vue [hunk 4]
```diff
@@ -142,73 +142,8 @@
...
-                                    <option value="text.ircv3.net">{{ $t("Text IRC Protocol") }}</option>
-                                    <option value="binary.ircv3.net">{{ $t("Binary IRC Protocol") }}</option>
-                                    <option value="v3.penguin-stats.live+proto">{{ $t("Penguin Statistics Live Protocol v3") }}</option>
-                                    <option value="TLCP-2.4.0.lightstreamer.com">TLCP 2.4.0</option>
-                                    <option value="TLCP-2.5.0.lightstreamer.com">TLCP 2.5.0</option>
-                                    <option value="Redfish">Redfish DSP0266</option>
-                                    <option value="bidib">webBiDiB</option>
-                                </select>
+                                <label for="ws_subprotocol" class="form-label">{{ $t("Subprotocol(s)") }}</label>
+                                <input id="ws_subprotocol" v-model="monitor.wsSubprotocol" type="text" class="form-control" :placeholder="$t('Optional')">
```
Comment (CommanderStorm) [inline src/pages/EditMonitor.vue]: lets add an example subprotocol usage to the placeholder instead to clairify this

```suggestion
                                <input id="ws_subprotocol" v-model="monitor.wsSubprotocol" type="text" class="form-control" placeholder="mielecloudconnect,soap">
```

File: server/monitor-types/websocket-upgrade.js (hunk 1 above)
Comment (PoleTransformer) [reply server/monitor-types/websocket-upgrade.js]: 0 disables timeouts. This should never happen in production because the front end enforces a lower limit. But yes I can set to default to 20s if its undefined for some reason.

File: src/lang/en.json (hunk 2 above)
Comment (PoleTransformer) [reply src/lang/en.json]: `For more information on status codes, please consult RFC 6455` is better phrasing. Thats why I left out "the".

Comment (CommanderStorm) [inline src/lang/en.json]: makes it simpler on our translators (+removes the mistake that I did in the last review)

```suggestion
    "wsCodeDescription": "For more information on status codes, please consult {rfc6455}",
```

File: src/pages/EditMonitor.vue [hunk 5]
```diff
@@ -889,6 +824,36 @@
...
+                                        :preselect-first="false"
+                                        :max-height="600"
+                                        :taggable="true"
+                                    ></VueMultiselect>
+
+                                    <div class="form-text">
+                                        {{ $t("acceptedStatusCodesDescription") }}
+                                    </div>
+                                    <i18n-t tag="div" class="form-text" keypath="wsCodeDescription">
+                                        <template #documentation>
```
Comment (CommanderStorm) [inline src/pages/EditMonitor.vue]:
```suggestion
                                        <template #rfc6455>
```

File: server/monitor-types/websocket-upgrade.js [hunk 6]
```diff
@@ -1,6 +1,26 @@
...
+    1009: "Message Too Big",
+    1010: "Mandatory Extension Missing",
+    1011: "Internal Error",
+    1012: "Service Restart",
+    1013: "Try Again Later",
+    1014: "Bad Gateway",
+    1015: "TLS Handshake Failed",
+    3000: "Unauthorized",
+    3003: "Forbidden",
+    3008: "Timeout",
```
[the remark this answers is not in the document]
Comment (PoleTransformer) [reply server/monitor-types/websocket-upgrade.js:22]: Want to keep the output as close as possible to IANA. Update some err msgs such as 1015 to be more clear on issue.

**Comment by CommanderStorm** [comment]
Re:CI-fail

- https://github.com/louislam/uptime-kuma/pull/6413/files#r2655809963

**Review by CommanderStorm — APPROVED** [review]
Nice work 👍🏻 

> [!TIP]
> For the future: I would appreciate if we split up PRs to only touching one thing, this is 3-in-1, so next time lets split such things into two ^^
