### PR TITLE
fix: correct SevenIO notification receiver field name

### LINKED ISSUE #6344: SevenIO Notification Receiver (to) missing
### 📑 I have found these related issues/pull requests

No Issue or PR found

### 🛡️ Security Policy

- [x] I have read and agree to Uptime Kuma's [Security Policy](https://github.com/louislam/uptime-kuma/security/policy).

### 📝 Description

Using Version 2.02, newly configured SevenIO SMS notification doesn't work.

According the sevenio debugger the receiver number is missing in the json file, but it's provided in uptime-kuma.
output from sevenio debugger:

`{"from":"Uptime A38","text":"Your service Testl went down at 2025-11-12 08:52:46 (Europe/Zurich). Error: Down"}`

in my opinion the above json should look like this:

`{"from":"Uptime A38","to":"410790000000","text":"Your service Testli went down at 2025-11-12 08:52:46 (Europe/Zurich). Error: Down"}`

### 👟 Reproduction steps

- Create new notification of type SevenIO
- Fill in your API Key, Sender and Receiver Number
- Assign the notification to a test service
- Produce down event
- Check Sevenio API Debugger

### 👀 Expected behavior

SMS received by SevenIO

### 😓 Actual Behavior

No SMS is sent by SevenIO

### 🐻 Uptime-Kuma Version

2.02

### 💻 Operating System and Arch

Docker Image

### 🌐 Browser

Microsoft Edge

### 🖥️ Deployment Environment

- **Runtime Environment**:
  - Docker: Version `X.X.X` (Build `Y.Y.Y`)
  - Docker Compose: Version `X.X.X`
  - Portainer (BE/CE): Version `X.X.X` (LTS: Yes/No)
  - MariaDB: Version `X.X.X` (LTS: Yes/No)
  - Node.js: Version `X.X.X` (LTS: Yes/No)
  - Kubernetes (K3S/K8S): Version `X.X.X` (LTS: Yes/No, via `[method/tool]`)
- **Database**:
  - SQLite: Embedded
  - MariaDB: Embedded/External
- **Database Storage**:
  - **Filesystem**:
    - Linux: ext4/XFS/Btrfs/ZFS/F2FS
    - macOS: APFS/ HFS+
    - Windows: NTFS/ReFS
  - **Storage Medium**: HDD/eMMC/SSD/NVMe
- **Uptime Kuma Setup**:
  - Number of monitors: `X`

### 📝 Relevant log output

```bash session

```

### PR DESCRIPTION
**Pull request by cl77**
## Summary
This PR fixes the SevenIO SMS notification feature by correcting the field name mismatch between the Vue component and the backend notification provider.

## Problem
The SevenIO notification component was using `sevenioReceiver` in the Vue template, but the backend provider expects `sevenioTo`. This caused the receiver phone number to be missing from the API payload, preventing SMS notifications from being sent.

## Changes
- Changed `v-model="$parent.notification.sevenioReceiver"` to `v-model="$parent.notification.sevenioTo"` in `src/components/notifications/SevenIO.vue`

## Test Plan
1. Configure a SevenIO notification with a receiver phone number
2. Trigger a down/up event
3. Verify that the SMS is sent successfully with the receiver number included in the API payload

Fixes #6344

### CODE REVIEW

**Review by CommanderStorm — CHANGES_REQUESTED** [review]
Good catch!

Please change it in the backend though as `sevenioReceiver` will have been written to the db by users who have set this up in v2.

File: src/components/notifications/SevenIO.vue [hunk 1]
```diff
@@ -14,7 +14,7 @@
 
     <div class="mb-3">
         <label for="sevenio-receiver" class="form-label">{{ $t("receiverSevenIO") }}</label>
-        <input id="sevenio-receiver" v-model="$parent.notification.sevenioReceiver" type="number" class="form-control" required autocomplete="false" placeholder="0123456789">
+        <input id="sevenio-receiver" v-model="$parent.notification.sevenioTo" type="number" class="form-control" required autocomplete="false" placeholder="0123456789">
```
Comment (CommanderStorm) [inline src/components/notifications/SevenIO.vue]:
```suggestion
        <input id="sevenio-receiver" v-model="$parent.notification.sevenioReceiver" type="number" class="form-control" required autocomplete="false" placeholder="0123456789">
```
