### PR TITLE
fix: allow for private domains like example.local and others

### LINKED ISSUE #6682: Don't domain expiry warn on `.local` and similar domains
### 📑 I have found these related issues/pull requests

I was not able to find any directly related to this. The closest I could find was https://github.com/louislam/uptime-kuma/issues/5400. But this is actually about mDNS, not my issue.

### 🛡️ Security Policy

- [x] I have read and agree to Uptime Kuma's [Security Policy](https://github.com/louislam/uptime-kuma/security/policy).

### 📝 Description

I get a lot of warnings about local not being supported. I believe this is because I use k3s and monitor services. An example of one of my monitors:

http://homeassistant.homeassistant.svc.cluster.local:8123

This is not mDNS, and works perfectly fine. DNS resolution is being handled by k3s. This should not result in a warning as it is an acceptable way to do monitoring.

### 👟 Reproduction steps

Create a monitor that ends in .local. Watch the logs.

### 👀 Expected behavior

Either this should not warn, or have some option to say "local allowed" to disable these messages.

### 😓 Actual Behavior

The logs will have a lot of unnecessary logging noise with warnings that are not really warnings.

### 🐻 Uptime-Kuma Version

2.1.0-beta.1

### 💻 Operating System and Arch

Ubuntu 24.04.3 LTS on Proxmox

### 🌐 Browser

Google Chrome 143.0.7499.193 (Official Build) (arm64) 

### 🖥️ Deployment Environment

- **Runtime Environment**:
  - Kubernetes (K3S/K8S): Version `v1.33.2+k3s1`
- **Database**:
  - MariaDB: Embedded
- **Database Storage**:
  - **Filesystem**:
    - Linux: ext4 and CEPH
  - **Storage Medium**: SSD/NVMe
- **Uptime Kuma Setup**:
  - Number of monitors: `98`

### 📝 Relevant log output

```bash session
2026-01-12T05:08:38-05:00 [DOMAIN] WARN: local is not supported. File a bug report if you believe it should be.
2026-01-12T05:08:42-05:00 [DOMAIN] WARN: local is not supported. File a bug report if you believe it should be.
2026-01-12T05:08:42-05:00 [DOMAIN] WARN: local is not supported. File a bug report if you believe it should be.
2026-01-12T05:08:43-05:00 [DOMAIN] WARN: local is not supported. File a bug report if you believe it should be.
2026-01-12T05:08:44-05:00 [DOMAIN] WARN: local is not supported. File a bug report if you believe it should be.
2026-01-12T05:08:44-05:00 [DOMAIN] WARN: local is not supported. File a bug report if you believe it should be.
2026-01-12T05:08:45-05:00 [DOMAIN] WARN: local is not supported. File a bug report if you believe it should be.
2026-01-12T05:08:46-05:00 [DOMAIN] WARN: local is not supported. File a bug report if you believe it should be.
2026-01-12T05:08:46-05:00 [DOMAIN] WARN: local is not supported. File a bug report if you believe it should be.
2026-01-12T05:08:47-05:00 [DOMAIN] WARN: local is not supported. File a bug report if you believe it should be.
2026-01-12T05:08:47-05:00 [DOMAIN] WARN: local is not supported. File a bug report if you believe it should be.
2026-01-12T05:09:02-05:00 [DOMAIN] WARN: local is not supported. File a bug report if you believe it should be.
2026-01-12T05:09:08-05:00 [DOMAIN] WARN: null is not supported. File a bug report if you believe it should be.
2026-01-12T05:09:09-05:00 [DOMAIN] WARN: null is not supported. File a bug report if you believe it should be.
```

### PR DESCRIPTION
**Pull request by iotux**
# Summary

In this pull request, the following changes are made:
- "if (tld.domain)" and "if (!tld.publicSuffix)" is replaced by "if (!tld.iCann) in "domain_expiry.js"

  This change prevent domains like "example.local" and myserver from being added to domain expiry monitoring and not being thrown.
  The "if (!tld.isIcann) also guaratees that only domains listed in ICANN's database are candidates for domain expiry monitoring

- Resolves #6682 

<details>
<summary>Please follow this checklist to avoid unnecessary back and forth (click to expand)</summary>

- [ ] ⚠️ If there are Breaking change (a fix or feature that alters existing functionality in a way that could cause issues) I have called them out
- [ ] 🧠 I have disclosed any use of LLMs/AI in this contribution and reviewed all generated content.
      I understand that I am responsible for and able to explain every line of code I submit.
- [x] 🔍 Any UI changes adhere to visual style of this project.
- [x] 🛠️ I have self-reviewed and self-tested my code to ensure it works as expected.
- [x] 📝 I have commented my code, especially in hard-to-understand areas (e.g., using JSDoc for methods).
- [x] 🤖 I added or updated automated tests where appropriate.
- [ ] 📄 Documentation updates are included (if applicable).
- [ ] 🧰 Dependency updates are listed and explained.
- [x] ⚠️ CI passes and is green.

</details>

### CODE REVIEW

File: test/backend-test/test-domain.js [hunk 1]
```diff
@@ -96,65 +96,33 @@ describe("Domain Expiry", () => {
...
-                    type: "http",
-                    url: "https://example.x",
-                    domainExpiryNotification: true,
-                };
-                await assert.rejects(
-                    async () => await DomainExpiry.checkSupport(monitor),
-                    (error) => {
-                        assert.strictEqual(error.constructor.name, "TranslatableError");
-                        assert.strictEqual(error.message, "domain_expiry_public_suffix_too_short");
+                        assert.strictEqual(error.message, "domain_expiry_unsupported_is_icann");
```
Comment (CommanderStorm) [inline test/backend-test/test-domain.js:141]: this should trigger the `domain_expiry_unsupported_is_ip` error instead.
-> Please reorder accoringly

File: server/model/domain_expiry.js [hunk 2]
```diff
@@ -159,11 +159,8 @@ class DomainExpiry extends BeanModel {
         const tld = parseTld(target);
 
         // Avoid logging for incomplete/invalid input while editing monitors.
-        if (!tld.domain) {
-            throw new TranslatableError("domain_expiry_unsupported_invalid_domain", { hostname: tld.hostname });
-        }
-        if (!tld.publicSuffix) {
-            throw new TranslatableError("domain_expiry_unsupported_public_suffix", { publicSuffix: tld.publicSuffix });
+        if (!tld.isIcann) {
+            throw new TranslatableError("domain_expiry_unsupported_is_icann", { publicSuffix: tld.hostname });
```
Comment (CommanderStorm) [inline server/model/domain_expiry.js]: If we do this, it needs to be moved down.
The more specific errors are otherwise ignored.

We should check in the following order instead:
- `isIP`
- `isPrivate`
- `isIcann`

If this is not done this way, this makes our error messages less actionable than it needs to be.

I don't know if missing `domain` or `publicSuffix` should be an error still before the `isIcann` check.

File: src/lang/en.json [hunk 3]
```diff
@@ -1300,6 +1300,7 @@
     "domain_expiry_unsupported_invalid_domain": "The configured value \"{hostname}\" is not a valid domain name",
     "domain_expiry_public_suffix_too_short": "\".{publicSuffix}\" is too short for a top level domain",
     "domain_expiry_unsupported_public_suffix": "The domain \"{domain}\" does not have a valid public suffix",
+    "domain_expiry_unsupported_is_icann": "The domain \"{domain}\" is not a candidate for domain expiry monitoring",
```
Comment (CommanderStorm) [inline src/lang/en.json]: - domain is not a parameter that is provided to this
- I think this needs a polishing pass in what the error message is. "not a candidate" is very non-specific or actionable

Comment (CommanderStorm) [inline src/lang/en.json]: if you remove translations above, they should also be removed here

**Review by CommanderStorm — COMMENTED** [review]
Thanks, the PR is now in a reviewable state

I don't currently think this change is 100% an improvement and needs a bit more work to be an actual improvement.

File: server/model/domain_expiry.js (hunk 2 above)
Comment (iotux) [reply server/model/domain_expiry.js]: I have moved isIP to top and the check for < 2 suffix before isIcann becaus isIcann will always be false with suffixes not registered with ICANN.

- isIp
- publicSuffix.length < 2
- isIcann

I have also not tested for  isPrivate, because I have not been able to find any domain where isPrivate === true.
The question is if publicSuffix.length test is needed at all, since a 1 character suffix is valid in a private domain name. Like other private domain names, it will always be caught by the isIcann test

Comment (CommanderStorm) [reply server/model/domain_expiry.js]: Sorry, it seems that I misunderstood isPrivate, that is indeed irellevant.

https://github.com/remusao/tldts/blob/78c02754c7d3c13338464b9104ea795ae1aa6386/README.md

File: test/backend-test/test-domain.js [hunk 4]
```diff
@@ -11,6 +11,7 @@ const { Settings } = require("../../server/settings");
 const { setSetting } = require("../../server/util-server");
 const dayjs = require("dayjs");
 dayjs.extend(require("dayjs/plugin/utc"));
+const TranslatableError = require("../../server/translatable-error");
```
Comment (CommanderStorm) [inline test/backend-test/test-domain.js]:
```suggestion
```

File: src/lang/en.json [hunk 5]
```diff
@@ -1296,10 +1296,9 @@
     "labelDomainNameExpiryNotification": "Domain Name Expiry Notification",
     "domainExpiryDescription": "Trigger notification when domain names expires in:",
     "domain_expiry_unsupported_monitor_type": "Domain expiry monitoring is not supported for this monitor type",
```
Comment (CommanderStorm) [inline src/lang/en.json:1298]:
```suggestion
    "domain_expiry_unsupported_monitor_type": "Domain expiry monitoring is not supported for this monitor type",
    "domain_expiry_unsupported_missing_target": "No valid domain or hostname is configured for this monitor",
```

File: test/backend-test/test-domain.js (hunk 4 above)
Comment (CommanderStorm) [inline test/backend-test/test-domain.js]:
```suggestion
```

File: src/lang/en.json [hunk 6]
```diff
@@ -1299,7 +1299,7 @@
     "domain_expiry_unsupported_missing_target": "No valid domain or hostname is configured for this monitor",
     "domain_expiry_unsupported_invalid_domain": "The configured value \"{hostname}\" is not a valid domain name",
     "domain_expiry_public_suffix_too_short": "\".{publicSuffix}\" is too short for a top level domain",
-    "domain_expiry_unsupported_public_suffix": "The domain \"{domain}\" does not have a valid public suffix",
+    "domain_expiry_unsupported_is_icann": "The domain \"{domain}\" is not a candidate for domain expiry monitoring",
```
Comment (CommanderStorm) [inline src/lang/en.json]:
```suggestion
    "domain_expiry_unsupported_is_icann": "The domain \"{domain}\" is not a candidate for domain expiry monitoring, because its public suffix \".{publicSuffix}\" is not ICAN",
```

File: server/model/domain_expiry.js [hunk 7]
```diff
@@ -159,20 +159,16 @@ class DomainExpiry extends BeanModel {
...
         if (tld.isIp) {
             throw new TranslatableError("domain_expiry_unsupported_is_ip", { hostname: tld.hostname });
         }
-
         // No one-letter public suffix exists; treat this as an incomplete/invalid input while typing.
         if (tld.publicSuffix.length < 2) {
             throw new TranslatableError("domain_expiry_public_suffix_too_short", { publicSuffix: tld.publicSuffix });
         }
+        if (!tld.isIcann) {
+            throw new TranslatableError("domain_expiry_unsupported_is_icann", { domain: tld.domain });
```
Comment (CommanderStorm) [inline server/model/domain_expiry.js]:
```suggestion
            throw new TranslatableError("domain_expiry_unsupported_is_icann", { domain: tld.domain, publicSuffix: tld.publicSuffix });
```

File: src/lang/en.json [hunk 8]
```diff
@@ -1363,4 +1363,4 @@
     "None (Successful Connection)": "None (Successful Connection)",
     "expectedTlsAlertDescription": "Select the TLS alert you expect the server to return. Use {code} to verify mTLS endpoints reject connections without client certificates. See {link} for details.",
     "TLS Alert Spec": "RFC 8446"
-}
+}
```
Comment (CommanderStorm) [inline src/lang/en.json]:
```suggestion
}

```

File: src/lang/en.json [hunk 9]
```diff
@@ -1299,7 +1299,7 @@
     "domain_expiry_unsupported_missing_target": "No valid domain or hostname is configured for this monitor",
     "domain_expiry_unsupported_invalid_domain": "The configured value \"{hostname}\" is not a valid domain name",
```
Comment (CommanderStorm) [inline src/lang/en.json]:
```suggestion
```

Comment (iotux) [reply src/lang/en.json]: What is going on? I have several times validated en.json with jq, but I still get error when running "node extra/check-lang-json.js ":

File en.json is not formatted correctly.

Comment (CommanderStorm) [reply src/lang/en.json]: the newline change at the end of the file

Comment (CommanderStorm) [reply src/lang/en.json]: should likely have an autofix, does not currently
