### PR TITLE
Updated croner to 8.1.0 and fixed "recurring-interval" type maintenance

### LINKED ISSUE #4634: Recuring Interval Maintenances display wrong dates in the maintenance list
### 📑 I have found these related issues/pull requests

NONE

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Trying to add a Recuring Interval Maintenance and it seems that it gets the wrong dates.

E.g. trying to add this maintenance on `04/07/2024`
uptime1

It shows wrong data here.
uptime2

### 👟 Reproduction steps

Add a recuring interval maintenance e.g. running once every 7 days starting from a specific date and after it ads it, it displays the wrong data in the Maintenance list.

### 👀 Expected behavior

It should show the right date which we have added in the first step.

### 😓 Actual Behavior

It shows the wrong date.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 22.04 LTS

### 🌐 Browser

Google Chrome Version 123.0.6312.86 (Official Build) (64-bit)

### 🖥️ Deployment Environment

- Runtime: NodeJS v20.12.0
- Database: sqlite/embedded
- Filesystem used to store the database on: ext4 on SSD
- number of monitors: 7

### 📝 Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by buzzinJohnnyBoi**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

Fixes #4634 
Possibly #4930

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

File: server/model/maintenance.js [hunk 1]
```diff
@@ -253,6 +253,10 @@ class Maintenance extends BeanModel {
                         duration = this.duration * 1000;
                     }
 
+                    if (duration === undefined && this.strategy === "recurring-interval") {
```
Comment (CommanderStorm) [inline server/model/maintenance.js:256]: I need a bit of help understanding the `if`-clause you added 😅:
Is this not already covered by the `if` or `else` branch above?

File: server/model/maintenance.js [hunk 2]
```diff
@@ -263,9 +267,21 @@ class Maintenance extends BeanModel {
...
+                    this.beanMeta.job = new Cron(this.cron, {
+                        timezone: await this.getTimezone(),
+                        interval: this.interval_day * 24 * 60 * 60,
+                        startAt: startDateTime.toISOString(),
+                    }, startEvent);
+                } else {
+                    this.beanMeta.job = new Cron(this.cron, {
+                        timezone: await this.getTimezone(),
+                    }, startEvent);
+                }
```
Comment (CommanderStorm) [inline server/model/maintenance.js:284]: nit: For these if-statements, I like to pull code which can be shared out, but am fine with your solution.
(feel free to accept/reject the below attached suggestion)

```suggestion
                const startDate = dayjs(this.startDate);
                const [ hour, minute ] = this.startTime.split(":");
                const startDateTime = startDate.hour(hour).minute(minute);
                const cronerOptions = {
                    timezone: await this.getTimezone(),
                    startAt: startDateTime.toISOString(),
                };
                if (this.strategy === "recurring-interval") {
                    cronerOptions.interval = this.interval_day * 24 * 60 * 60;
                }
                this.beanMeta.job = new Cron(this.cron, cronerOptions, startEvent);
```

File: server/model/maintenance.js [hunk 3]
```diff
@@ -395,10 +411,7 @@ class Maintenance extends BeanModel {
         } else if (!this.strategy.startsWith("recurring-")) {
             this.cron = "";
         } else if (this.strategy === "recurring-interval") {
-            let array = this.start_time.split(":");
-            let hour = parseInt(array[0]);
-            let minute = parseInt(array[1]);
-            this.cron = minute + " " + hour + " */" + this.interval_day + " * *";
+            this.cron = "* * * * *"; // Because it is interval, it will be calculated in the run function
```
Comment (CommanderStorm) [inline server/model/maintenance.js:414]: nit: think this can be bit rephrased, feel free to reject

```suggestion
            // For intervals, the pattern is calculated in the run function as the interval-option is set
            this.cron = "* * * * *";
```

**Review by CommanderStorm — COMMENTED** [review]
overall looks good to me.
I have left a question below

File: server/model/maintenance.js (hunk 1 above)
Comment (buzzinJohnnyBoi) [reply server/model/maintenance.js:256]: Hi, @CommanderStorm, so above is an `if` - `else if` - `else`, and the `else if` is when `this.end_date` is set, and it calculates if `this.end_date` will be before the end of the interval. If it is not, then `this.duration` is left `undefined`.
I guess my solution is not the best one, I was not sure if it was left `undefined` for some other purpose, but if it is not, then I guess the `else if` should look something like this:

```javascript
else if (this.end_date) {
    let d = dayjs(this.end_date).diff(dayjs(), "second");
    if (d < this.duration) {
        duration = d * 1000;
    }
    else {
        duration = this.duration * 1000;
    }
}
```
Let me know if you want me to make this change.

File: server/model/maintenance.js (hunk 2 above)
Comment (buzzinJohnnyBoi) [reply server/model/maintenance.js:284]: I realize that your example is a little cleaner, but I think I will just leave it because startAt is not used for anything accept for recurring-interval.

File: package.json [hunk 4]
```diff
@@ -89,7 +89,7 @@
         "command-exists": "~1.2.9",
         "compare-versions": "~3.6.0",
         "compression": "~1.7.4",
-        "croner": "~6.0.5",
+        "croner": "^8.1.0",
```
Comment (louislam) [inline package.json:92]:
```suggestion
        "croner": "~8.1.0",
```

File: server/model/maintenance.js (hunk 1 above)
Comment (CommanderStorm) [reply server/model/maintenance.js:256]: I think that is better.
`duration` is never explicitly checked for undefined => I think this is a bug ^^

While you are at it, I think that while `if`/... clause would be way better if extracted into a function `this.duration = this.inferDuration()`
That way the controll flow is not as confusing in the future..

Comment (buzzinJohnnyBoi) [reply server/model/maintenance.js]:
```javascript
    inferDuration(customDuration) {
        // Check if duration is still in the window. If not, use the duration from the current time to the end of the window
        if (customDuration > 0) {
            return customDuration;
        } else if (this.end_date) {
            let d = dayjs(this.end_date).diff(dayjs(), "second");
            if (d < this.duration) {
                return d * 1000;
            }
        }
        return this.duration * 1000;
    }
````
[Code here](https://github.com/buzzinJohnnyBoi/uptime-kuma/blob/30f7b4898758ea5422983d00a3d3a3597e7e1524/server/model/maintenance.js#L319C5-L330C6)\
Lmk if this is good.

File: package-lock.json [hunk 5]
```diff
@@ -24,7 +24,7 @@
                 "command-exists": "~1.2.9",
                 "compare-versions": "~3.6.0",
                 "compression": "~1.7.4",
-                "croner": "~6.0.5",
+                "croner": "^8.1.0",
```
Comment (CommanderStorm) [inline package-lock.json:27]: You forgot to run `npm install` ^^

```suggestion
                "croner": "~8.1.0",
```

**Comment by CommanderStorm** [comment]
Thanks for the fix! 🎉 



> [!NOTE]
> This PR is part of the [`v2.0` merge window](https://github.com/louislam/uptime-kuma/milestone/24) => see #4500 for the bugs that need to be addressed before we can ship this release ^^

<sub>All changes in this PR are small and uncontroversial ⇒ merging with junior maintainer approval</sub>
