### PR TITLE
Fix: Filtering works with group monitor

### LINKED ISSUE #3445: Filtering cannot display monitors within a group
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

_No response_

### 👟 Reproduction steps

1. Create a Group monitor A
2. Create a monitor B, put monitor in the group monitor A
3. Pause monitor B
4. In monitor list filters, select Active -> Paused
5. Observer that monitor B does not show up

### 👀 Expected behavior

Monitor list should show the monitor group which contains the monitor satisfying the filtering criteria

### 😓 Actual Behavior

Monitor list does not show the monitor group which contains the monitor satisfying the filtering criteria

### 🐻 Uptime-Kuma Version

master

### 💻 Operating System and Arch

Windows 11 x64

### 🌐 Browser

Microsoft Edge

### 🐋 Docker Version

_No response_

### 🟩 NodeJS Version

_No response_

### 📝 Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by chakflying**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Fixes #3445

- Refactor the process of search and filtering to a single loop over the monitor list
- Renamed prop `isSearch` to `showPathName` to be more clear on functionality

Unfortunately, enabling search/filtering will flatten all group structures. Doesn't look amazing but again can't think of an easy fix.

Also fixes bug:

- monitor.active now returns true/false instead of 1/0. Update sort function to reflect this.

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- User interface (UI)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [ ] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

### CODE REVIEW

File: src/components/MonitorList.vue [hunk 1]
```diff
@@ -81,31 +81,71 @@ export default {
...
+                        monitor.status = this.$root.lastHeartbeatList[monitor.id].status;
+                    }
+                    statusMatch = this.filterState.status.includes(monitor.status);
+                }
+
+                // filter by active
+                let activeMatch = true;
+                if (this.filterState.active != null && this.filterState.active.length > 0) {
+                    activeMatch = this.filterState.active.includes(monitor.active);
+                }
```
Comment (CommanderStorm) [inline src/components/MonitorList.vue:119]: You seem to like the "if.. assign" pattern (don't know the real name)

I would argue that this can be simplified to
```suggestion
                const shouldFilterByActive = this.filterState.active != null;
                let activeMatch = shouldFilterByActive && this.filterState.active.includes(monitor.active);
```

(code-style => feel free to overrule ^^)

Comment (CommanderStorm) [reply src/components/MonitorList.vue:119]: I have updated the proposed code (this time with a boolean table):
|               | `filterCanBeActive` true | `filterCanBeActive` false |
|---------------|---------|----------|
| `includes` true  | true    | true     |
| `includes` false | false   | true     |

Comment (chakflying) [reply src/components/MonitorList.vue:119]: I guess I see that this makes it a bit shorter, but I don't think this makes it more readable, which is important to me.

Comment (CommanderStorm) [reply src/components/MonitorList.vue:119]: True, the `!filterCanBeActive` is hideous.
I proposed this to be explicit about not changing any logic this time (introducing bugs is worse than hard to maintain code) ^^

I think it is more readable if `!filterCanBeActive` is integrated to `filterCannotBeActive` and the expression changed in the corresponding way.

As stated above, if you feel differently, just overrule my comment and close this review-comment

**Review by Computroniks — COMMENTED** [review]
Just some (IMO) odd looking whitespace
