### PR TITLE
fix: show actual bind address in startup logs

### LINKED ISSUE #6956: Clarify bind address in startup logs
### 📑 I have found these related issues/pull requests

-

### 🛡️ Security Policy

- [x] I have read and agree to Uptime Kuma's [Security Policy](https://github.com/louislam/uptime-kuma/security/policy).

### 📝 Description

When starting Uptime Kuma, the following is logged:

    INFO: Open http://localhost:3001 in your browser

This implies the process bound to loopback only, but that is not the case, which could cause a security issue.

### 👟 Reproduction steps

-

### 👀 Expected behavior

-

### 😓 Actual Behavior

-

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

-

### 🌐 Browser

-

### 🖥️ Deployment Environment

-

### 📝 Relevant log output

```bash session

```

### PR DESCRIPTION
**Pull request by mixelburg**
Fixes #6956

When no custom hostname is configured, the server binds to all interfaces (`0.0.0.0`), but the startup log either showed just the port number or `localhost`, which could be misleading — implying the server is only accessible on loopback.

This updates both `server.js` and `setup-database.js` to display `0.0.0.0` as the bind address when no hostname is explicitly set, accurately reflecting that the server is listening on all interfaces.

### CODE REVIEW

File: server/utils/simple-migration-server.js [hunk 1]
```diff
@@ -67,7 +67,17 @@ class SimpleMigrationServer {
...
                     log.info("migration", `Migration server is running on http://${hostname}:${port}`);
                 } else {
-                    log.info("migration", `Migration server is running on http://localhost:${port}`);
+                    log.info("migration", `Migration server is running on:`);
+                    log.info("migration", `  Local:   http://localhost:${port}`);
+                    const { networkInterfaces } = require("os");
+                    const nets = networkInterfaces();
+                    for (const name of Object.keys(nets)) {
+                        for (const net of nets[name]) {
+                            if (!net.internal && net.family === "IPv4") {
```
Comment (CommanderStorm) [inline server/utils/simple-migration-server.js]: why the ipv4 check?
We likely should show all the interaces we bound to.

Comment (louislam) [reply server/utils/simple-migration-server.js]: also we have function in js. Copy-and-paste is not a good idea, or it is AI code?

Comment (mixelburg) [reply server/utils/simple-migration-server.js]: f, ur right
