### PR TITLE
fix: update dns monitor to evaluate full response list on CAA resolver_type

### LINKED ISSUE #6519: DNS Monitor only checks first CAA record when multiple records exist
### 📑 I have found these related issues/pull requests

This issue relates specifically to CAA records. Doing a [search for CAA issues](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue%20state%3Aclosed%20CAA) yields few results.

The only PR I can see which may have address this issue #3919 was closed. 

### 🛡️ Security Policy

- [x] I have read and agree to Uptime Kuma's [Security Policy](https://github.com/louislam/uptime-kuma/security/policy).

### 📝 Description

When monitoring DNS records where multiple CAA records exist, the DNS monitor appears to only check the first record returned rather than all records.

### 👟 Reproduction steps

1. Create multiple CAA records
2. Configure DNS monitor with expected value matching one specific record
3. Observe that test results are inconsistent across multiple checks

### 👀 Expected behavior

When multiple CAA records exist, the monitor should check all returned records against the expected value, not just the first one.

### 😓 Actual Behavior

- Check passes intermittently depending on which record DNS returns first
- Test fails when a different record is returned first
- DNS servers can return records in any order, causing inconsistent results

### 🐻 Uptime-Kuma Version

2.0.2

### 💻 Operating System and Arch

OSx Tahoe Version 26.1 (25B78)

### 🌐 Browser

Version 143.0.7499.147 (Official Build) (arm64)

### 🖥️ Deployment Environment

Docker OSX

## Debugging

I have a root domain with 3 CAA records defined. 

```javascript
[
  { critical: 0, issuewild: 'letsencrypt.org' },
  { critical: 0, issue: 'letsencrypt.org' },
  { critical: 0, issue: 'REDACTED' }
]
```

It appears the relevant source code can be found here where it explicitly pulls the first record and assumes the key `issue`

https://github.com/louislam/uptime-kuma/blob/d23ff8c4860b09cdd8c57ba9ab6ced5321dd3782/server/monitor-types/dns.js#L53-L54

This causes my health check to fail intermittently due to the non-deterministic response ordering.

I had hoped to use the condition "Record contains" option but it throws an `indexOf` error. 

Image

I'm not sure how best to implement this in a backward compatible way.

I see for other record types the use of `some`

```diff
# Could we do something like this?
- conditionsResult = handleConditions({ record: dnsRes[0].issue });
+ conditionsResult = dnsRes.some(record => handleConditions({ record: dnsRes[0].issue }));
``` 

An issue I see what that approach is the assumption of the key `issue`. 

According to the [spec](https://datatracker.ietf.org/doc/html/rfc6844#section-7.2) there is `issue`, `issueWild`, and `iodef`. 

Looking for suggestions on how to proceed!

Thanks!

### PR DESCRIPTION
**Pull request by am17torres**
## 📝 Summary of changes done and why they are done

When multiple CAA records exist, the monitor should check all returned records against the expected value, not just the first one.

## 📋 Related issues

- Resolves #6519

## 📄 Checklist

<details>
<summary>Please follow this checklist to avoid unnecessary back and forth (click to expand)</summary>

- [x] ⚠️ If there are Breaking change (a fix or feature that alters existing functionality in a way that could cause issues) I have called them out
- [x] 🔍 My code adheres to the style guidelines of this project.
- [x] 🦿 I have indicated where (if any) I used an LLM for the contributions
Not Applicable
- [x] ✅ I ran ESLint and other code linters for modified files.
- [x] ⚠️ My changes generate no new warnings.
- [x] 🛠️ I have reviewed and tested my code.
- [x] 📝 I have commented my code, especially in hard-to-understand areas (e.g., using JSDoc for methods).
- [x] 🤖 My code needed automated testing. I have added them (this is an optional task).
- [x] 📄 Documentation updates are included (if applicable).
- [x] 🔒 I have considered potential security impacts and mitigated risks.
- [x] 🧰 Dependency updates are listed and explained.

</details>

### CODE REVIEW

File: server/monitor-types/dns.js [hunk 1]
```diff
@@ -50,8 +50,8 @@ class DnsMonitorType extends MonitorType {
                 break;
 
             case "CAA":
-                dnsMessage = dnsRes[0].issue;
-                conditionsResult = handleConditions({ record: dnsRes[0].issue });
+                dnsMessage = `Records: ${dnsRes.map(record => record.issue).filter(Boolean).join(" | ")}`;
```
Comment (am17torres) [inline server/monitor-types/dns.js:55]: `.filter(Boolean)` was added because some CAA records do not contain an issue key, resulting in a blank list item. 

Hypothetical `dnsRes`

```javascript
[
  { critical: 0, issuewild: 'letsencrypt.org' },
  { critical: 0, issue: 'letsencrypt.org' },
  { critical: 0, issue: 'foo.org' }
]
```

without filter

```
Records: | letsencrypt.org | foo.org
```

with filter

```
Records: letsencrypt.org | foo.org
```

Comment (CommanderStorm) [reply server/monitor-types/dns.js:55]: can you add a code comment to explain this? I think otherwise future devs might remove this

**Review by CommanderStorm — APPROVED** [review]
Thank you ❤️

**Comment by am17torres** [comment]
> Thank you ❤️

Any time! Thank you for making it easy to contribute.

**Comment by am17torres** [comment]
What's the release cycle for uptime kuma? 
Will I be able to docker pull this change anytime soon?

**Comment by CommanderStorm** [comment]
I merged it into beta.0, so it will be in 2.1 when louis publishes it in the new year (?).
In general how often we release could be improved.

If you really need it, you can ping him and he can publish a nightly, that is just running a npm command, so not a lot of work.

**Comment by am17torres** [comment]
Not urgent at all. Hoping to deploy this sometime in mid-January. I was just exploring this tool to see if it's fit for purpose. So far so good!
