### PR TITLE
Perform sanity check on uptime for status page

### LINKED ISSUE #2628: uptime value exceeds 100%
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

image

### 👟 Reproduction steps

I don't know.

### 👀 Expected behavior

The max. uptime value should be 100%.

### 😓 Actual Behavior

The max. uptime value is over 100%.

### 🐻 Uptime-Kuma Version

1.19.3

### 💻 Operating System and Arch

Raspbian bullseye

### 🌐 Browser

Google Chrome, Safari, Mozilla Firefox

### 🐋 Docker Version

2.14.1

### 🟩 NodeJS Version

_No response_

### 📝 Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Computroniks**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Commit message:
Fixes #2628
A sanity check is performed when calculating the uptime of a monitor on status page. If it is greater than 100%, we just show 100%. This hasn't been implemented on the dashboard at the request of @louislam due to concerns it would make debugging more difficult in future if changes were made to the uptime calculation.

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- User interface (UI)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings

### CODE REVIEW

File: src/components/Uptime.vue [hunk 1]
```diff
@@ -33,7 +33,13 @@ export default {
             let key = this.monitor.id + "_" + this.type;
 
             if (this.$root.uptimeList[key] !== undefined) {
-                return Math.round(this.$root.uptimeList[key] * 10000) / 100 + "%";
+                let result = Math.round(this.$root.uptimeList[key] * 10000) / 100;
+                // Only perform sanity check on status page. See louislam/uptime-kuma#2628
+                if (this.$route.path.startsWith("/status")) {
```
Comment (louislam) [inline src/components/Uptime.vue:38]: `result + "%"` is duplicated, it could be simplified by merging into one condition.

```
if (this.$route.path.startsWith("/status") && result > 100) {
```

Comment (tminei) [reply src/components/Uptime.vue:38]: Reducing code is not always about simplifying it

Comment (Computroniks) [reply src/components/Uptime.vue]: I have gone and updated this
