### PR TITLE
Fix: Getting TLS certificate through proxy & prometheus update

### LINKED ISSUE #4693: Error in working with local proxy
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

After updating to version 1.23.12, an error was found (Cannot set properties of undefined (setting 'valid') when working with local proxies
Rolling back to version 1.23.11 solved this problem.

I'm launching it in the docker.

### 📝 Error Message(s) or Log

_No response_

### 🐻 Uptime-Kuma Version

1.23.12

### 💻 Operating System and Arch

Debian (docker)

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime: Docker 26.0.1 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

### LINKED ISSUE #4698: prometheus metric `monitor_cert_days_remaining` missing after update to 1.23.12
### 📑 I have found these related issues/pull requests

- https://github.com/louislam/uptime-kuma/issues/4693
- https://github.com/louislam/uptime-kuma/issues/2455

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

after update to 1.23.12 monitor_cert_days_remaining is not exported anymore, it is still shown in the dashboard.

### 👟 Reproduction steps

use 1.23.12 and create monitor for an https website

### 👀 Expected behavior

monitor_cert_days_remaining is exported as in version 1.23.11

### 😓 Actual Behavior

the monitor_cert_days_remaining metric is missing

### 🐻 Uptime-Kuma Version

1.23.12

### 💻 Operating System and Arch

debian/docker

### 🌐 Browser

chrome

### 🖥️ Deployment Environment

- Runtime: Docker 24.0.7
- Database: embedded
- Filesystem used to store the database on:  
- number of monitors: 5

### 📝 Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by chakflying**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

Fixes #4693
Fixes #4698
Also handles the issue in #3551 correctly

I think I found a way to listen for the `secureConnect` event, which eliminates the messy 2-step process of the previous fix. I also restored the old method of checking for the `tlsSocket` after the response is received, since the `proxy-agent` does not seem to work with the `keylog` event, but we can still obtain the TLS information through the socket.

Feel free to test.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

### CODE REVIEW

File: server/model/monitor.js [hunk 1]
```diff
@@ -512,10 +512,22 @@ class Monitor extends BeanModel {
...
                     }
 
-                    let tlsInfo;
-                    // Store tlsInfo when key material is received
-                    options.httpsAgent.on("keylog", (line, tlsSocket) => {
-                        tlsInfo = checkCertificate(tlsSocket);
+                    let tlsInfo = {};
+                    // Store tlsInfo when secureConnect event is emitted
+                    // The keylog event listener is a workaround to access the tlsSocket
+                    options.httpsAgent.once("keylog", async (line, tlsSocket) => {
```
Comment (CommanderStorm) [inline server/model/monitor.js:518]: good catch on the `on` vs `once` difference.
Did not know said function. We are likely misusing `on` in other places as well

File: server/model/monitor.js [hunk 2]
```diff
@@ -527,19 +539,22 @@ class Monitor extends BeanModel {
...
-
-                        if (tlssocket) {
-                            tlsInfo.valid = tlssocket.authorized || false;
-                        }
-
-                        await this.updateTlsInfo(tlsInfo);
-                        if (!this.getIgnoreTls() && this.isEnabledExpiryNotification()) {
-                            log.debug("monitor", `[${this.name}] call checkCertExpiryNotifications`);
-                            await this.checkCertExpiryNotifications(tlsInfo);
+                        if (tlsInfo.valid === undefined) {
```
Comment (CommanderStorm) [inline server/model/monitor.js:545]: nit: What do you think?
should we merge these two if statements into one line? (removing the one above which I can't comment on)

```suggestion
                    if (this.getUrl()?.protocol === "https:" && tlsInfo.valid === undefined) {
```

**Review by CommanderStorm — COMMENTED** [review]
I don't like that now we have the same function twice.
Could we extract this to a function or is this small enough to not cause a problem?

File: server/model/monitor.js (hunk 1 above)
Comment (chakflying) [reply server/model/monitor.js:518]: Shouldn't be a big problem, the socket handlers do need `on` since they are repeatedly handling messages.
