### PR TITLE
fix: clearing heartbeats on paused monitors leaves them paused

### LINKED ISSUE #6895: Bug: Monitor restarts after deleting heartbeats while paused
### 📑 I have found these related issues/pull requests

I have checked, but couldn’t find anything similar.

### 🛡️ Security Policy

- [x] I have read and agree to Uptime Kuma's [Security Policy](https://github.com/louislam/uptime-kuma/security/policy).

### 📝 Description

When a monitor is paused and the heartbeats are subsequently deleted, the monitor automatically starts again. This behavior is unexpected.

<details>
  <summary>screencast (click to expand)</summary>
  <p>

https://github.com/user-attachments/assets/89d19260-619a-4e73-aad5-54135b723519

  </p>
</details>

### 👟 Reproduction steps

1. Create a monitor, for example an HTTP(s) monitor for `google.com` that sends a request every 20 seconds.
2. Wait until several heartbeats have been recorded.
3. Pause the monitor.
   3.1 A toast notification confirms that the monitor is paused.
4. Delete the heartbeats.
   4.1 A toast notification confirms that the monitor status is `[Up] 200 - OK`.
5. Refresh the page. You will see that the monitor has automatically started again.

**Result:** The heartbeats are successfully deleted, but the monitor automatically restarts.

### 👀 Expected behavior

The monitor should remain paused after the heartbeats are deleted.

### 😓 Actual Behavior

The monitor restarts when the heartbeats are deleted and does not remain paused.

### 🐻 Uptime-Kuma Version

2.1.0

### 💻 Operating System and Arch

Ubuntu 24.04.3 LTS (GNU/Linux 6.8.0-94-generic x86_64)

### 🌐 Browser

Brave 1.86.148 - Chromium: 144.0.7559.133 (Official Build) (64-bit)

### 🖥️ Deployment Environment

- **Runtime Environment**:
  - Docker: Version `26.1.0` (Build `9714adc`)
  - Docker Compose: Version `2.26.1`
  - Portainer (BE): Version `2.33.6` (LTS: Yes)
  - MariaDB: Version `12.1.2` (LTS: Yes)
- **Database**:
  - MariaDB: External
- **Database Storage**:
  - **Filesystem**:
    - Linux: ext4
  - **Storage Medium**: SSD
- **Uptime Kuma Setup**:
  - Number of monitors: `99`

### 📝 Relevant log output

```bash session
No relevant log output for this issue.
```

### PR DESCRIPTION
**Pull request by bruce691**
# Summary

In this pull request, the following changes are made:

- Prevent `clearHeartbeats` from restarting a paused monitor by only restarting when the monitor is still active in the database.

- Resolves #6895

<details>
<summary>Please follow this checklist to avoid unnecessary back and forth (click to expand)</summary>

- [ ] ⚠️ If there are Breaking change (a fix or feature that alters existing functionality in a way that could cause issues) I have called them out
- [x] 🧠 I have disclosed any use of LLMs/AI in this contribution and reviewed all generated content.
      I understand that I am responsible for and able to explain every line of code I submit.
- [ ] 🔍 Any UI changes adhere to visual style of this project.
- [x] 🛠️ I have self-reviewed and self-tested my code to ensure it works as expected.
- [ ] 📝 I have commented my code, especially in hard-to-understand areas (e.g., using JSDoc for methods).
- [ ] 🤖 I added or updated automated tests where appropriate.
- [ ] 📄 Documentation updates are included (if applicable).
- [ ] 🧰 Dependency updates are listed and explained.
- [ ] ⚠️ CI passes and is green.

</details>

## Screenshots for Visual Changes

https://github.com/user-attachments/assets/57db2bdc-e13b-4487-9892-ad0d5569da75

### CODE REVIEW

File: server/server.js [hunk 1]
```diff
@@ -1650,7 +1650,9 @@ let needSetup = false;
 
                 await UptimeCalculator.clearStatistics(monitorID);
 
-                if (monitorID in server.monitorList) {
+                const monitor = await R.findOne("monitor", " id = ? ", [monitorID]);
+
+                if (monitor?.active && monitorID in server.monitorList) {
```
Comment (ryangurn) [inline server/server.js]: should `monitorId in server.monitorList` be the first condition to evaluate in the if statement?

**Comment by bruce691** [comment]
Thanks @CommanderStorm

**Comment by louislam** [comment]
It is fixed partially. Let me finish the missing part. Also I don't like the `monitor` object got from db again.
