### PR TITLE
Fix: [MariaDB] Unable to clean up heartbeat data

### LINKED ISSUE #5381: MariaDB Error: "LIMIT & IN/ALL/ANY/SOME subquery" Not Supported
### 📑 I have found these related issues/pull requests

I have checked, but couldn’t find anything similar.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

While executing a `DELETE` query on the `heartbeat` table, the following error
occurs:

This version of MariaDB doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'

### Query

```sql
DELETE FROM heartbeat
WHERE monitor_id = 1
AND important = 0
AND time < DATE_ADD(NOW(), INTERVAL -24 HOUR)
AND id NOT IN (
    SELECT id
    FROM heartbeat
    WHERE monitor_id = 1
    ORDER BY time DESC
    LIMIT 100
)
```

### Error Details

- **Error Code:** ER_NOT_SUPPORTED_YET
- **SQL State:** 42000
- **MySQL Version:** MariaDB 11.6.2

### Stack Trace

```log
Error at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:738:17)
```

The current version of MariaDB does not support combining `LIMIT` with `IN/ALL/ANY/SOME` subqueries, which causes this error.

### Suggested Fix

Modify the query to avoid using `LIMIT` inside the `IN` clause.

Example suggestion:

```sql
DELETE FROM heartbeat
WHERE monitor_id = 1
AND important = 0
AND time < DATE_ADD(NOW(), INTERVAL -24 HOUR)
AND id NOT IN (
    SELECT id
    FROM (
        SELECT id
        FROM heartbeat
        WHERE monitor_id = 1
        ORDER BY time DESC
        LIMIT 100
    ) AS limited_ids
)
```

This structure ensures compatibility by avoiding the direct use of `LIMIT` in the outer `IN` clause.

### 👟 Reproduction steps

```docker-compose.yml
---
networks:
  uptime-kuma-beta_net:
    attachable: false
    internal: false
    external: false
    name: uptime-kuma-beta
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.3.0/24
          ip_range: 172.20.3.0/24
          gateway: 172.20.3.1
    driver_opts:
      com.docker.network.bridge.default_bridge: "false"
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
      com.docker.network.bridge.name: "uptime-kuma"
      com.docker.network.driver.mtu: "1500"
    labels:
      com.uptime-kuma-beta.network.description: "is an isolated bridge network."

services:
  uptime-kuma-beta_db:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "2"
    stop_grace_period: 1m
    container_name: uptime-kuma-beta_db
    image: mariadb:latest
    pull_policy: if_not_present
    volumes:
      - /docker/uptime-kuma-beta/db:/var/lib/mysql
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/Amsterdam
      MYSQL_ROOT_PASSWORD: "ThisIsADemoRootPassword"
      MYSQL_DATABASE: "uptime_kuma_db"
      MYSQL_USER: "uptime-kuma"
      MYSQL_PASSWORD: "ThisIsADemoPassword"
    command:
      [
        "--transaction-isolation=READ-COMMITTED",
        "--log-bin=binlog",
        "--binlog-format=ROW",
      ]
    hostname: uptime-kuma-beta_db
    networks:
      uptime-kuma-beta_net:
        ipv4_address: 172.20.3.2
    security_opt:
      - no-new-privileges:true
    labels:
      com.uptime-kuma-beta.db.description: "is an MySQL database."
    healthcheck:
      disable: true

  uptime-kuma-beta_app:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "2"
    stop_grace_period: 1m
    container_name: uptime-kuma-beta
    image: louislam/uptime-kuma:2.0.0-beta.0
    pull_policy: if_not_present
    depends_on:
      uptime-kuma-beta_db:
        condition: service_started
    links:
      - uptime-kuma-beta_db
    volumes:
      - /docker/uptime-kuma-beta/app:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/local/share/ca-certificates:/app/data/docker-tls
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/Amsterdam
      # This is a certificate authority for demonstration purposes.
      # NODE_EXTRA_CA_CERTS: /app/data/docker-tls/root_ca_demo_cert.pem
      MYSQL_HOST: "uptime-kuma-beta_db"
      MYSQL_PORT: 3306
      MYSQL_NAME: "uptime_kuma_db"
      MYSQL_USER: "uptime-kuma"
      MYSQL_PASSWORD: "ThisIsADemoPassword"
    domainname: status.local
    hostname: status
    networks:
      uptime-kuma-beta_net:
        ipv4_address: 172.20.3.3
    ports:
      - "3001:3001/tcp" # HTTP
      - "3001:3001/udp" # HTTP
    security_opt:
      - no-new-privileges:true
    labels:
      com.docker.compose.project: "uptime-kuma-beta"
      com.uptime-kuma-beta.description:
        "is an self-hosted monitoring tool that allows you to monitor uptime,
        status, and notifications for various services and domains."
    healthcheck:
      disable: true
```

### 👀 Expected behavior

The query should execute successfully, deleting older entries from the `heartbeat` table while keeping the most recent 100 entries.

### 😓 Actual Behavior

The query fails due to the unsupported subquery syntax in MariaDB.

### 🐻 Uptime-Kuma Version

2.0.0-beta.0

### 💻 Operating System and Arch

Ubuntu Server 24.04.1 LTS (GNU/Linux 6.8.0-49-generic x86_64)

### 🌐 Browser

Brave Version 1.73.91 Chromium: 131.0.6778.85 (Official Build) (64-bit)

### 🖥️ Deployment Environment

- **Runtime:** Docker version 26.1.0, build 9714adc
- **Runtime:** docker-compose version 1.29.2, build unknown
- **Runtime:** Portainer Business Edition version 2.21.4
- **Runtime:** MariaDB 11.6.2
- **Database:** (external)
- **Filesystem used for the database:** Linux/ext4 on an SSD
- **Number of monitors:** 92

### 📝 Relevant log output

```shell
Trace: Error:
                DELETE FROM heartbeat
                WHERE monitor_id = 1
                AND important = 0
                AND time < DATE_ADD(NOW(), INTERVAL -24 HOUR)
                AND id NOT IN (
                    SELECT id
                    FROM heartbeat
                    WHERE monitor_id = 1
                    ORDER BY time DESC
                    LIMIT 100
                )
             - This version of MariaDB doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:738:17)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_NOT_SUPPORTED_YET',
  errno: 1235,
  sqlState: '42000',
  sqlMessage: "This version of MariaDB doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'",
  sql: '\n' +
    '                DELETE FROM heartbeat\n' +
    '                WHERE monitor_id = 1\n' +
    '                AND important = 0\n' +
    '                AND time < DATE_ADD(NOW(), INTERVAL -24 HOUR)\n' +
    '                AND id NOT IN (\n' +
    '                    SELECT id\n' +
    '                    FROM heartbeat\n' +
    '                    WHERE monitor_id = 1\n' +
    '                    ORDER BY time DESC\n' +
    '                    LIMIT 100\n' +
    '                )\n' +
    '            '
}
    at process.unexpectedErrorHandler (/app/server/server.js:1872:13)
    at process.emit (node:events:519:28)
    at emitUnhandledRejection (node:internal/process/promises:250:13)
    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)
    at processPromiseRejections (node:internal/process/promises:470:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
```

### PR DESCRIPTION
**Pull request by louislam**
# Description

Fixes #5381

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [ ] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

File: server/database.js [hunk 1]
```diff
@@ -892,11 +892,13 @@ class Database {
                 AND important = 0
                 AND time < ${sqlHourOffset}
                 AND id NOT IN (
-                    SELECT id
-                    FROM heartbeat
-                    WHERE monitor_id = ?
-                    ORDER BY time DESC
-                    LIMIT ?
+                    SELECT id FROM (
```
Comment (CommanderStorm) [inline server/database.js:895]: Let's document why this is done this way too

```suggestion
                    SELECT id FROM ( -- written this way for Maria's support
```

**Review by CommanderStorm — CHANGES_REQUESTED** [review]
