### PR TITLE
Fix: Change `montior`.`ip_family` data type from boolean to string

### LINKED ISSUE #6121: Cannot select IP-family - container
### 📑 I have found these related issues/pull requests

https://github.com/louislam/uptime-kuma/pull/5880 Feature IP-family for HTTPS monitors

### 🛡️ Security Policy

- [x] I have read and agree to Uptime Kuma's [Security Policy](https://github.com/louislam/uptime-kuma/security/policy).

### 📝 Description

`2.0.0-beta4` introduces the selection of IP-families in a HTTPS monitor

Running `uptime-kuma` in a container, does not work as expected.
Instead the below log message is thrown and the save does not happen.

### 👟 Reproduction steps

- start `uptime-kuma` container tag: `beta-rootless` - 2.0.0-beta4
- `podman run -d --restart=always --cap-add=NET_RAW -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:beta-rootless`
- run the initial setup with integrated MariaDB
- add HTTPS monitor
- check that it works
- edit HTTPS monitor and select `IPv6` for the IP-family
- save monitor -> error is thrown

### 👀 Expected behavior

- IPv6 family is saved and monitor uses IPv6 for this monitor
- Works running `uptime-kuma` in a standalone installation
-

### 😓 Actual Behavior

- does not save the monitor
- does not save the IP-family

### 🐻 Uptime-Kuma Version

2.0.0-beta.4

### 💻 Operating System and Arch

Fedora 42 - server

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- **Runtime Environment**:
  - Podman
      - Client:        Podman Engine
      - Version:       5.6.1
      - Built:         Thu Sep  4 02:00:00 2025
      - Build Origin:  Fedora Project
      - OS/Arch:       linux/amd64
- **Database**:
  - MariaDB: Embedded
- **Database Storage**:
  - **Filesystem**:
    - Linux: Btrfs
  - **Storage Medium**: NVMe
- **Uptime Kuma Setup**:
  - Number of monitors: `3`

### 📝 Relevant log output

```bash session
25-09-14T09:11:40+02:00 [MONITOR] INFO: Added Monitor: 3 User ID: 1
2025-09-14T09:11:45+02:00 [MONITOR] INFO: Get Monitor: 3 User ID: 1
2025-09-14T09:11:52+02:00 [MONITOR] ERROR: Error: update `monitor` set `name` = 'uptime.kuma.pet', `active` = 1, `user_id` = 1, `interval` = 60, `url` = 'https://uptime.kuma.pet/', `type` = 'http', `weight` = 2000, `hostname` = NULL, `port` = NULL, `created_date` = '2025-09-14 07:11:40', `keyword` = NULL, `maxretries` = 0, `ignore_tls` = false, `upside_down` = false, `maxredirects` = 10, `accepted_statuscodes_json` = '[\"200-299\"]', `dns_resolve_type` = 'A', `dns_resolve_server` = '1.1.1.1', `dns_last_result` = NULL, `retry_interval` = 60, `push_token` = NULL, `method` = 'GET', `body` = NULL, `headers` = NULL, `basic_auth_user` = NULL, `basic_auth_pass` = NULL, `docker_host` = NULL, `docker_container` = '', `proxy_id` = NULL, `expiry_notification` = false, `mqtt_topic` = '', `mqtt_success_message` = '', `mqtt_username` = '', `mqtt_password` = '', `database_connection_string` = NULL, `database_query` = NULL, `auth_method` = NULL, `auth_domain` = NULL, `auth_workstation` = NULL, `grpc_url` = NULL, `grpc_protobuf` = NULL, `grpc_body` = NULL, `grpc_metadata` = NULL, `grpc_method` = NULL, `grpc_service_name` = NULL, `grpc_enable_tls` = false, `radius_username` = NULL, `radius_password` = NULL, `radius_calling_station_id` = NULL, `radius_called_station_id` = NULL, `radius_secret` = NULL, `resend_interval` = 0, `packet_size` = 56, `game` = NULL, `http_body_encoding` = 'json', `description` = NULL, `tls_ca` = NULL, `tls_cert` = NULL, `tls_key` = NULL, `parent` = NULL, `invert_keyword` = false, `json_path` = '$', `expected_value` = NULL, `kafka_producer_topic` = NULL, `kafka_producer_brokers` = '[]', `kafka_producer_ssl` = false, `kafka_producer_allow_auto_topic_creation` = false, `kafka_producer_sasl_options` = '{\"mechanism\":\"None\"}', `kafka_producer_message` = NULL, `oauth_client_id` = NULL, `oauth_client_secret` = NULL, `oauth_token_url` = NULL, `oauth_scopes` = NULL, `oauth_auth_method` = 'client_secret_basic', `timeout` = 48, `gamedig_given_port_only` = true, `mqtt_check_type` = 'keyword', `remote_browser` = NULL, `snmp_oid` = NULL, `snmp_version` = '2c', `json_path_operator` = '==', `cache_bust` = false, `conditions` = '[]', `rabbitmq_nodes` = '[]', `rabbitmq_username` = '', `rabbitmq_password` = '', `smtp_security` = NULL, `ping_count` = 3, `ping_numeric` = true, `ping_per_request_timeout` = 2, `ip_family` = 'ipv4', `oauth_audience` = NULL, `mqtt_websocket_path` = '' where `id` = 3 - Incorrect integer value: 'ipv4' for column `kuma`.`monitor`.`ip_family` at row 1
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:740:17)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/base/connection.js:475:34)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/base/connection.js:93:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/base/connection.js:100:25)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
  errno: 1366,
  sqlState: '22007',
  sqlMessage: "Incorrect integer value: 'ipv4' for column `kuma`.`monitor`.`ip_family` at row 1",
  sql: 'update `monitor` set `name` = \'uptime.kuma.pet\', `active` = 1, `user_id` = 1, `interval` = 60, `url` = \'https://uptime.kuma.pet/\', `type` = \'http\', `weight` = 2000, `hostname` = NULL, `port` = NULL, `created_date` = \'2025-09-14 07:11:40\', `keyword` = NULL, `maxretries` = 0, `ignore_tls` = false, `upside_down` = false, `maxredirects` = 10, `accepted_statuscodes_json` = \'[\\"200-299\\"]\', `dns_resolve_type` = \'A\', `dns_resolve_server` = \'1.1.1.1\', `dns_last_result` = NULL, `retry_interval` = 60, `push_token` = NULL, `method` = \'GET\', `body` = NULL, `headers` = NULL, `basic_auth_user` = NULL, `basic_auth_pass` = NULL, `docker_host` = NULL, `docker_container` = \'\', `proxy_id` = NULL, `expiry_notification` = false, `mqtt_topic` = \'\', `mqtt_success_message` = \'\', `mqtt_username` = \'\', `mqtt_password` = \'\', `database_connection_string` = NULL, `database_query` = NULL, `auth_method` = NULL, `auth_domain` = NULL, `auth_workstation` = NULL, `grpc_url` = NULL, `grpc_protobuf` = NULL, `grpc_body` = NULL, `grpc_metadata` = NULL, `grpc_method` = NULL, `grpc_service_name` = NULL, `grpc_enable_tls` = false, `radius_username` = NULL, `radius_password` = NULL, `radius_calling_station_id` = NULL, `radius_called_station_id` = NULL, `radius_secret` = NULL, `resend_interval` = 0, `packet_size` = 56, `game` = NULL, `http_body_encoding` = \'json\', `description` = NULL, `tls_ca` = NULL, `tls_cert` = NULL, `tls_key` = NULL, `parent` = NULL, `invert_keyword` = false, `json_path` = \'$\', `expected_value` = NULL, `kafka_producer_topic` = NULL, `kafka_producer_brokers` = \'[]\', `kafka_producer_ssl` = false, `kafka_producer_allow_auto_topic_creation` = false, `kafka_producer_sasl_options` = \'{\\"mechanism\\":\\"None\\"}\', `kafka_producer_message` = NULL, `oauth_client_id` = NULL, `oauth_client_secret` = NULL, `oauth_token_url` = NULL, `oauth_scopes` = NULL, `oauth_auth_method` = \'client_secret_basic\', `timeout` = 48, `gamedig_given_port_only` = true, `mqtt_check_type` = \'keyword\', `remote_browser` = NULL, `snmp_oid` = NULL, `snmp_version` = \'2c\', `json_path_operator` = \'==\', `cache_bust` = false, `conditions` = \'[]\', `rabbitmq_nodes` = \'[]\', `rabbitmq_username` = \'\', `rabbitmq_password` = \'\', `smtp_security` = NULL, `ping_count` = 3, `ping_numeric` = true, `ping_per_request_timeout` = 2, `ip_family` = \'ipv4\', `oauth_audience` = NULL, `mqtt_websocket_path` = \'\' where `id` = 3'
}
2025-09-14T09:11:52+02:00 [MONITOR] INFO: Get Monitor: 3 User ID: 1
2025-09-14T09:12:01+02:00 [MONITOR] ERROR: Error: update `monitor` set `name` = 'uptime.kuma.pet', `active` = 1, `user_id` = 1, `interval` = 60, `url` = 'https://uptime.kuma.pet/', `type` = 'http', `weight` = 2000, `hostname` = NULL, `port` = NULL, `created_date` = '2025-09-14 07:11:40', `keyword` = NULL, `maxretries` = 0, `ignore_tls` = false, `upside_down` = false, `maxredirects` = 10, `accepted_statuscodes_json` = '[\"200-299\"]', `dns_resolve_type` = 'A', `dns_resolve_server` = '1.1.1.1', `dns_last_result` = NULL, `retry_interval` = 60, `push_token` = NULL, `method` = 'GET', `body` = NULL, `headers` = NULL, `basic_auth_user` = NULL, `basic_auth_pass` = NULL, `docker_host` = NULL, `docker_container` = '', `proxy_id` = NULL, `expiry_notification` = false, `mqtt_topic` = '', `mqtt_success_message` = '', `mqtt_username` = '', `mqtt_password` = '', `database_connection_string` = NULL, `database_query` = NULL, `auth_method` = NULL, `auth_domain` = NULL, `auth_workstation` = NULL, `grpc_url` = NULL, `grpc_protobuf` = NULL, `grpc_body` = NULL, `grpc_metadata` = NULL, `grpc_method` = NULL, `grpc_service_name` = NULL, `grpc_enable_tls` = false, `radius_username` = NULL, `radius_password` = NULL, `radius_calling_station_id` = NULL, `radius_called_station_id` = NULL, `radius_secret` = NULL, `resend_interval` = 0, `packet_size` = 56, `game` = NULL, `http_body_encoding` = 'json', `description` = NULL, `tls_ca` = NULL, `tls_cert` = NULL, `tls_key` = NULL, `parent` = NULL, `invert_keyword` = false, `json_path` = '$', `expected_value` = NULL, `kafka_producer_topic` = NULL, `kafka_producer_brokers` = '[]', `kafka_producer_ssl` = false, `kafka_producer_allow_auto_topic_creation` = false, `kafka_producer_sasl_options` = '{\"mechanism\":\"None\"}', `kafka_producer_message` = NULL, `oauth_client_id` = NULL, `oauth_client_secret` = NULL, `oauth_token_url` = NULL, `oauth_scopes` = NULL, `oauth_auth_method` = 'client_secret_basic', `timeout` = 48, `gamedig_given_port_only` = true, `mqtt_check_type` = 'keyword', `remote_browser` = NULL, `snmp_oid` = NULL, `snmp_version` = '2c', `json_path_operator` = '==', `cache_bust` = false, `conditions` = '[]', `rabbitmq_nodes` = '[]', `rabbitmq_username` = '', `rabbitmq_password` = '', `smtp_security` = NULL, `ping_count` = 3, `ping_numeric` = true, `ping_per_request_timeout` = 2, `ip_family` = 'ipv6', `oauth_audience` = NULL, `mqtt_websocket_path` = '' where `id` = 3 - Incorrect integer value: 'ipv6' for column `kuma`.`monitor`.`ip_family` at row 1
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:740:17)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/base/connection.js:475:34)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/base/connection.js:93:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/base/connection.js:100:25)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
  errno: 1366,
  sqlState: '22007',
  sqlMessage: "Incorrect integer value: 'ipv6' for column `kuma`.`monitor`.`ip_family` at row 1",
  sql: 'update `monitor` set `name` = \'uptime.kuma.pet\', `active` = 1, `user_id` = 1, `interval` = 60, `url` = \'https://uptime.kuma.pet/\', `type` = \'http\', `weight` = 2000, `hostname` = NULL, `port` = NULL, `created_date` = \'2025-09-14 07:11:40\', `keyword` = NULL, `maxretries` = 0, `ignore_tls` = false, `upside_down` = false, `maxredirects` = 10, `accepted_statuscodes_json` = \'[\\"200-299\\"]\', `dns_resolve_type` = \'A\', `dns_resolve_server` = \'1.1.1.1\', `dns_last_result` = NULL, `retry_interval` = 60, `push_token` = NULL, `method` = \'GET\', `body` = NULL, `headers` = NULL, `basic_auth_user` = NULL, `basic_auth_pass` = NULL, `docker_host` = NULL, `docker_container` = \'\', `proxy_id` = NULL, `expiry_notification` = false, `mqtt_topic` = \'\', `mqtt_success_message` = \'\', `mqtt_username` = \'\', `mqtt_password` = \'\', `database_connection_string` = NULL, `database_query` = NULL, `auth_method` = NULL, `auth_domain` = NULL, `auth_workstation` = NULL, `grpc_url` = NULL, `grpc_protobuf` = NULL, `grpc_body` = NULL, `grpc_metadata` = NULL, `grpc_method` = NULL, `grpc_service_name` = NULL, `grpc_enable_tls` = false, `radius_username` = NULL, `radius_password` = NULL, `radius_calling_station_id` = NULL, `radius_called_station_id` = NULL, `radius_secret` = NULL, `resend_interval` = 0, `packet_size` = 56, `game` = NULL, `http_body_encoding` = \'json\', `description` = NULL, `tls_ca` = NULL, `tls_cert` = NULL, `tls_key` = NULL, `parent` = NULL, `invert_keyword` = false, `json_path` = \'$\', `expected_value` = NULL, `kafka_producer_topic` = NULL, `kafka_producer_brokers` = \'[]\', `kafka_producer_ssl` = false, `kafka_producer_allow_auto_topic_creation` = false, `kafka_producer_sasl_options` = \'{\\"mechanism\\":\\"None\\"}\', `kafka_producer_message` = NULL, `oauth_client_id` = NULL, `oauth_client_secret` = NULL, `oauth_token_url` = NULL, `oauth_scopes` = NULL, `oauth_auth_method` = \'client_secret_basic\', `timeout` = 48, `gamedig_given_port_only` = true, `mqtt_check_type` = \'keyword\', `remote_browser` = NULL, `snmp_oid` = NULL, `snmp_version` = \'2c\', `json_path_operator` = \'==\', `cache_bust` = false, `conditions` = \'[]\', `rabbitmq_nodes` = \'[]\', `rabbitmq_username` = \'\', `rabbitmq_password` = \'\', `smtp_security` = NULL, `ping_count` = 3, `ping_numeric` = true, `ping_per_request_timeout` = 2, `ip_family` = \'ipv6\', `oauth_audience` = NULL, `mqtt_websocket_path` = \'\' where `id` = 3'
}
```

### PR DESCRIPTION
**Pull request by louislam**
Fix #6121

Not tested on MySQL yet, feel free to help.

Also added "auto-select" for translation.

### CODE REVIEW

File: db/knex_migrations/2025-10-14-0000-add-ip-family-fix.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
+exports.up = function (knex) {
+    return knex.schema
+        .alterTable("monitor", function (table) {
+            // Fix ip_family, change to varchar instead of boolean
+            table.string("ip_family", 20).defaultTo(null).alter();
```
Comment (CommanderStorm) [inline db/knex_migrations/2025-10-14-0000-add-ip-family-fix.js]:
```suggestion
            // Fix ip_family, change to varchar instead of boolean
            // possible values are "ipv4" and "ipv6"
            table.string("ip_family", 4).defaultTo(null).alter();
```

**Comment by louislam** [comment]
Thanks for testing.
