### PR TITLE
fix: monitor graph gaps for sub-millisecond TCP pings

### LINKED ISSUE #7143: Monitors Graph Intermittent
### ⚠️ Please verify that your question has not already been reported

- [x] I have searched the [existing issues](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue%20sort%3Acreated-desc%20) and found no similar reports.

### 🛡️ Security Policy

- [x] I have read and agree to Uptime Kuma's [Security Policy](https://github.com/louislam/uptime-kuma/security/policy).

### 📝 Describe your problem

Hello,

I am running Uptime Kuma on Docker and migrated the Docker volume and the folder to a new server recently. 
I kept the existing monitors but updated the IPs to the new migrated environment. 

Interestingly, I see a bunch of TCP Port monitors looking like this:

Image

I've tried adding new monitors too, and they also perform the same
Any Ideas?

### 📝 Error Message(s) or Log

```bash session

```

### 🐻 Uptime-Kuma Version

2.2.0

### 💻 Operating System and Arch

Ubuntu 24.04.4 LTS

### 🌐 Browser

Firefox 148.0.2 (64-bit)

### 🖥️ Deployment Environment

- **Runtime Environment**:
  - Docker: Version 29.3.0
- **Database**:
  - SQLite: Embedded
- **Database Storage**:
  - **Filesystem**:
    - Linux: ext4
- **Uptime Kuma Setup**:
  - Number of monitors: 15

### PR DESCRIPTION
**Pull request by 0xRozier**
# Summary

In this pull request, the following changes are made:

- Change chart filter from `avgPing > 0` to `avgPing != null` in `PingChart.vue` so that 0ms ping values are rendered as data points instead of creating gaps in the graph.
- Add unit tests to verify that 0ms ping values are not filtered out.

TCP monitors on fast local networks (e.g. SSH on same-host VMs) can respond in <1ms. `Math.round()` converts these to 0ms, and the chart's `pushDatapoint()` method was filtering out `avgPing` values of 0 (treating them as `null`), creating intermittent gaps in the graph.

- Resolves #7143

<details>
<summary>Please follow this checklist to avoid unnecessary back and forth (click to expand)</summary>

- [x] ⚠️ If there are Breaking change (a fix or feature that alters existing functionality in a way that could cause issues) I have called them out
- [x] 🧠 I have disclosed any use of LLMs/AI in this contribution and reviewed all generated content.
      I understand that I am responsible for and able to explain every line of code I submit.
- [x] 🔍 Any UI changes adhere to visual style of this project.
- [x] 🛠️ I have self-reviewed and self-tested my code to ensure it works as expected.
- [x] 📝 I have commented my code, especially in hard-to-understand areas (e.g., using JSDoc for methods).
- [x] 🤖 I added or updated automated tests where appropriate.
- [ ] 📄 Documentation updates are included (if applicable).
- [ ] 🧰 Dependency updates are listed and explained.
- [ ] ⚠️ CI passes and is green.

</details>

## Screenshots for Visual Changes

- **UI Modifications**: Monitor graphs no longer show intermittent gaps for fast TCP connections (e.g. SSH on local network VMs).
- **Before**: See screenshot in issue #7143
- **After**: 

| Event              | Before                | After                |
| ------------------ | --------------------- | -------------------- |
| Graph continuity   | Before | <! image |

### CODE REVIEW

File: test/backend-test/test-ping-chart.js [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+const assert = require("node:assert");
+
+/**
+ * Extracts the ping value filtering logic from PingChart.vue pushDatapoint().
+ * This mirrors the condition: datapoint.up > 0 && datapoint.avgPing != null
+ * @param {object} datapoint Datapoint with up, avgPing, minPing, maxPing
+ * @returns {number|null} The avgPing value or null if filtered out
+ */
+function filterPingValue(datapoint) {
+    return datapoint.up > 0 && datapoint.avgPing != null ? datapoint.avgPing : null;
```
Comment (louislam) [inline test/backend-test/test-ping-chart.js:11]: This test is not actually testing the real code.

It is meaningless if someone modify the real code.
