### PR TITLE
Fix Group monitors to send notification after reaching maximum retires count

### LINKED ISSUE #6284: Group retry count not working, notification sent after single error
### 📑 I have found these related issues/pull requests

no

### 🛡️ Security Policy

- [x] I have read and agree to Uptime Kuma's [Security Policy](https://github.com/louislam/uptime-kuma/security/policy).

### 📝 Description

Image

I set the check frequency to 60 seconds and expected a notification only if errors persisted for 5 consecutive minutes, so I set the retry count to 5.
However, one item in the group encountered an error once and recovered in the next minute, yet I still received a notification.

### 👟 Reproduction steps

- Create a _Group_ monitor, set its _Retries_ to `5`, set a notification 
- Add a monitor to that group, set its _Retries_ to `0`, don't set any notification 
- That monitor encountered an error

### 👀 Expected behavior

The group goes error after the monitor in it error, but the notification is not sent.
After 5 errors of the group, the notification is sent.

### 😓 Actual Behavior

A notification is sent immediately after a single error.

### 🐻 Uptime-Kuma Version

2.0.2

### 💻 Operating System and Arch

debian 12

### 🌐 Browser

chrome

### 🖥️ Deployment Environment

not related

### 📝 Relevant log output

```bash session

```

### PR DESCRIPTION
**Pull request by MayMeow**
## 📋 Overview

- **What problem does this pull request address?**
  - The group monitors trigger a notification whenever one of the child monitors fails (goes to state `DOWN`). The group monitor ignored the maximum retries count setting.
- **What features or functionality does this pull request introduce or enhance?**
  - Group monitors now defer notifications the same way single monitors do. Previously `GroupMonitorType.check()` just set `heartbeat.status = DOWN` when a child failed, so the outer loop never hit the retry branch and fired alerts immediately.
  - The revised logic collects child statuses, keeps the group in `PENDING` while children are still retrying, and only throws when at least one child is truly `DOWN`. 
  - Throwing lets `Monitor.start(`)’s catch block increment retries and suppress notifications until the group hits its configured maxretries.
  - The heartbeat message now lists down/pending children, so once the retries are exhausted the alert includes actionable detail.

- Relates to #6284 
- Resolves #6284 

## 🛠️ Type of change

- [x] 🐛 Bugfix (a non-breaking change that resolves an issue)
- [ ] ✨ New feature (a non-breaking change that adds new functionality)
- [ ] ⚠️ Breaking change (a fix or feature that alters existing functionality in a way that could cause issues)
- [ ] 🎨 User Interface (UI) updates
- [ ] 📄 New Documentation (addition of new documentation)
- [ ] 📄 Documentation Update (modification of existing documentation)
- [ ] 📄 Documentation Update Required (the change requires updates to related documentation)
- [ ] 🔧 Other (please specify):
  - Provide additional details here.

## 📄 Checklist

- [ ] 🔍 My code adheres to the style guidelines of this project.
- [ ] 🦿 I have indicated where (if any) I used an LLM for the contributions
- [x] ✅ I ran ESLint and other code linters for modified files.
- [x] 🛠️ I have reviewed and tested my code.
- [x] 📝 I have commented my code, especially in hard-to-understand areas (e.g., using JSDoc for methods).
- [x] ⚠️ My changes generate no new warnings.
- [ ] 🤖 My code needed automated testing. I have added them (this is an optional task).
- [ ] 📄 Documentation updates are included (if applicable).
- [x] 🔒 I have considered potential security impacts and mitigated risks.
- [ ] 🧰 Dependency updates are listed and explained.
- [x] 📚 I have read and understood the [Pull Request guidelines](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#recommended-pull-request-guideline).

## 📷 Screenshots or Visual Changes

- The group goes down after the maximum number of retries if one of the child monitors is down.
- The group goes up when all the children's monitors are up.

image

- Status log includes also which children monitor has changed state

image

### CODE REVIEW

File: server/monitor-types/group.js [hunk 1]
```diff
@@ -11,35 +11,69 @@ class GroupMonitorType extends MonitorType {
...
+        if (worstStatus === UP) {
+            heartbeat.status = UP;
+            heartbeat.msg = "All children up and running";
+            return;
+        }
+
+        if (worstStatus === PENDING) {
             heartbeat.status = PENDING;
-            heartbeat.msg = "Group empty";
+            heartbeat.msg = pendingChildren.length > 0 ? `Pending child monitors: ${pendingChildren.join(", ")}` : "Child monitor pending";
```
[the remark this answers is not in the document]
Comment (CommanderStorm) [reply server/monitor-types/group.js]: I don't think this case can enven happen, or am I missing something?

```suggestion
            heartbeat.msg = `Pending child monitors: ${pendingChildren.join(", ")}`;
```

File: server/monitor-types/group.js [hunk 2]
```diff
@@ -11,35 +11,69 @@ class GroupMonitorType extends MonitorType {
...
+
+        heartbeat.status = DOWN;
+
+        const downList = downChildren.join(", ");
+        const pendingList = pendingChildren.join(", ");
+        let message = downList ? `Child monitors down: ${downList}` : "Child monitor down";
+
+        if (pendingChildren.length > 0) {
+            message += `; pending: ${pendingList}`;
         }
```
Comment (CommanderStorm) [inline server/monitor-types/group.js]: I think this can be simplified, right?

```suggestion
        let message = `Child monitors down: ${downChildren.join(", ")}`;

        if (pendingChildren.length > 0) {
            message += `; pending: ${pendingChildren.join(", ")}`;
        }
```

File: server/monitor-types/group.js [hunk 3]
```diff
@@ -11,35 +11,69 @@ class GroupMonitorType extends MonitorType {
...
+            return;
+        }
+
+        let worstStatus = UP;
+        const downChildren = [];
+        const pendingChildren = [];
+
+        for (const child of children) {
+            if (!child.active) {
+                // Ignore inactive children
```
Comment (CommanderStorm) [inline server/monitor-types/group.js]: Lets clarify this for future readers 😉 

```suggestion
                // Ignore inactive (=paused) children
```

**Review by CommanderStorm — APPROVED** [review]
Nice work.
Looks good to me, I have left one question for clarifyication.

Once that question is resolved, I would be happy to merge

File: server/monitor-types/group.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (maymeow) [reply server/monitor-types/group.js]: Yes you are right, I was unnecessary defensive here... I'll fix it

File: server/monitor-types/group.js (hunk 3 above)
Comment (maymeow) [reply server/monitor-types/group.js]: i have updated comment as proposed

File: server/monitor-types/group.js (hunk 2 above)
Comment (maymeow) [reply server/monitor-types/group.js]: also fixed this one....
