### PR TITLE
fix: idn ping errors

### LINKED ISSUE #3929: [dns] Uptime Kuma Unable to Track Internationalized Domain Names (IDNs)
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I've noticed that Uptime Kuma has difficulty tracking Internationalized Domain Names (IDNs) that contain non-ASCII characters like umlauts. Such domains typically get converted to Punycode (e.g., münchen.de becomes xn--mnchen-3ya.de) for DNS processing.

### 👟 Reproduction steps

1. Open Uptime Kuma.
2. Attempt to add monitoring for an IDN such as münchen.de.
3. Observe the behavior or any error messages.

### 👀 Expected behavior

Uptime Kuma should be able to correctly monitor the availability of IDNs by internally converting the domains to their Punycode form and using that for checking.

### 😓 Actual Behavior

Uptime Kuma fails to correctly monitor the availability of IDNs.

**Additional Information:**

- This issue might be related to how Uptime Kuma performs DNS queries for domains with non-ASCII characters.
- It would be helpful if Uptime Kuma performed an internal conversion to Punycode before attempting to check the availability of an IDN.

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Ubuntu 20.04 with Plesk / MacOS 14.0

### 🌐 Browser

Firefox 118.0.2 (64-Bit)

### 🐋 Docker Version

_No response_

### 🟩 NodeJS Version

v18.17.1

### 📝 Relevant log output

_No response_

### LINKED ISSUE #6661: Ping monitor, fails to punicode decode international domain names like münchen.de
### 📑 I have found these related issues/pull requests

- #570 is old and closed, but may be related

### 🛡️ Security Policy

- [x] I have read and agree to Uptime Kuma's [Security Policy](https://github.com/louislam/uptime-kuma/security/policy).

### 📝 Description

Adding a  ping monitor for "münchen.de" results in the following message
```bash
2026-01-09T12:23:06+01:00 [MONITOR] WARN: Monitor #33 'münchen.de': Failing: ping: münchen.de: Parameter string not correctly encoded
```

### 👟 Reproduction steps

Adding a Ping monitor with any IDN domain name

### 👀 Expected behavior

Adding a Ping monitor for a IDN domain should behave equally to any other domain name

### 😓 Actual Behavior

Image

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Ubuntu 25.10

### 🌐 Browser

Any

### 🖥️ Deployment Environment

- **Runtime Environment**:
  - Node.js: Version `X.X.X` (LTS: Yes/No)
- **Database**:
  - SQLite: Embedded
- **Database Storage**:
  - **Filesystem**:
    - Linux: ext4
  - **Storage Medium**: NVMe
- **Uptime Kuma Setup**:
  - Number of monitors: `1`

### 📝 Relevant log output

```bash session
2026-01-09T12:23:06+01:00 [MONITOR] WARN: Monitor #33 'münchen.de': Failing: ping: münchen.de: Parameter string not correctly encoded
```

### PR DESCRIPTION
**Pull request by iotux**
<sub>ℹ️ To keep reviews fast and effective, please make sure you’ve [read our pull request guidelines](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma)</sub>

## 📝 Summary of changes done and why they are done

The purpose of this PR is to allow for adding Ping type monitors with IDN domains.
To achieve this, I have added IDN translation by calling URL(address) and extracting the hostname from the result.

During testing, I became aware of the URL call imposes square brackes around IPv6 addresses.
I have therefore added a block that remove those bracket to make it compatible with a shell ping command.

I have also added a similar IDN translation to  the defaultFriendlyName function for monitor.hostname in EditMonitor.js.
This change will show the punycode in the Friendly Name input field in other hostname related monitor types like it is done for the HTTP(s) monitor types.

## 📋 Related issues

- Relates to #570 (old and closed issue 
- Resolves #6661 
- Resolves #3929 

## 📄 Checklist

<details>
<summary>Please follow this checklist to avoid unnecessary back and forth (click to expand)</summary>

- [ ] ⚠️ If there are Breaking change (a fix or feature that alters existing functionality in a way that could cause issues) I have called them out
- [ ] 🧠 I have disclosed any use of LLMs/AI in this contribution and reviewed all generated content.
      I understand that I am responsible for and able to explain every line of code I submit.
- [x] 🔍 My code adheres to the style guidelines of this project.
- [x] ⚠️ My changes generate no new warnings.
- [x] 🛠️ I have reviewed and tested my code.
- [x] 📝 I have commented my code, especially in hard-to-understand areas (e.g., using JSDoc for methods).
- [ ] 🤖 I added or updated automated tests where appropriate.
- [ ] 📄 Documentation updates are included (if applicable).
- [x] 🔒 I have considered potential security impacts and mitigated risks.
- [ ] 🧰 Dependency updates are listed and explained.

</details>

## 📷 Screenshots or Visual Changes

- **UI Modifications**: Highlight any changes made to the user interface.

Punycode will show in the Friendly Name fields for hostname related monitors the same way as HTTP(s) monitor types
There are no other visible changes to the user interface

### CODE REVIEW

**Comment by iotux** [comment]
> could you add a test so that the ping monitor does not backslides on this?

Done!
image

This pr will also fix issue #3929

image

File: src/pages/EditMonitor.vue [hunk 1]
```diff
@@ -2260,7 +2260,13 @@ export default {
 
         defaultFriendlyName() {
             if (this.monitor.hostname) {
-                return this.monitor.hostname;
+                try {
+                    // Convert IDN to punycode
+                    const url = new URL(`http://${this.monitor.hostname}`);
+                    return url.hostname;
```
Comment (louislam) [inline src/pages/EditMonitor.vue]: Why also need to convert the default friendly name to punycode? I think the friendly name is for human reading, it is not necessary to convert.

Image

File: test/backend-test/test-util-server.js
Comment (CommanderStorm) [inline test/backend-test/test-util-server.js:1]: This test isn’t really validating the behavior I’m describing.

At the moment it only checks that the function:

- does not throw, or
- if it does throw, that the error message isn’t a specific one

That makes this more of a "nothing catastrophically broke”"test than a "this works and will keep working" test. It helps catch bit-level corruption, but it doesn’t meaningfully protect the intended behavior.

We should make this more robust by asserting correct handling of valid, real-world inputs. In particular, instead of using two semi-invalid values, let's explicitly test:

- an IDN domain like münchen.de
- a valid IPv6 address

That way the test actually verifies functionality and will catch regressions if parsing or validation logic changes in the future.

Comment (CommanderStorm) [inline test/backend-test/test-util-server.js:1]: lets rename this to `test-util-server.js`, I don't want to have too specific of a filename

Comment (iotux) [reply test/backend-test/test-util-server.js:1]: Done!

File: src/pages/EditMonitor.vue (hunk 1 above)
Comment (iotux) [reply src/pages/EditMonitor.vue]: It was done to make it conformant with the different HTTP monitor types.
As it is, it now shows punycode the same was as the different HTTP monitor types.
I believe it is actually useful to show the punycode, at least for the DNS monitor.
And after all, it is there only until the user enter the field and starts writing anything else.
I will revert it if needed. Just make the decision

File: test/backend-test/test-util-server.js [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+            await pingAsync("münchen.de", false, 1, "", true, 56, 1, 1);
+        } catch (e) {
+            if (e.message.includes("Parameter string not correctly encoded")) {
+                assert.fail("Ping failed with encoding error: IDN was not converted");
+            }
+            assert.ok(
+                e.message.includes("xn--mnchen-3ya.de"),
+                `Error message should contain "xn--mnchen-3ya.de". Got: ${e.message}`
+            );
+        }
```
Comment (CommanderStorm) [inline test/backend-test/test-util-server.js]: Please assert using assert.throws if you expect an error.
This way, we actually know that it happened.

Currently, this code might fail or succeed.
This is what I meant by the first part of my previous feedback, could have been clearer.

Comment (iotux) [reply test/backend-test/test-util-server.js]: Working on it :)

**Review by CommanderStorm — APPROVED** [review]
From my side this LGTM now.
It needs an approval from louis for a merge

**Comment by iotux** [comment]
> From my side this LGTM now. It needs an approval from louis for a merge

I had already pushed an update when I noticed your message.
I admittedly had a bit of struggle with the unusual MacOS error message, but I found a workaround for that.
Now all tests have passed :)

File: src/pages/EditMonitor.vue (hunk 1 above)
Comment (louislam) [reply src/pages/EditMonitor.vue]: Yes, please revert it. I prefer all to show non-punycode friendly name.

Comment (iotux) [reply src/pages/EditMonitor.vue]: Done!

**Review by louislam — APPROVED** [review]
