### PR TITLE
fix: Explicitly pushing status=down now bypasses retry logic and goes directly to `DOWN`

### LINKED ISSUE #6406: Explicitly pushing down status does not work anymore
### 📑 I have found these related issues/pull requests

- https://github.com/louislam/uptime-kuma/issues/5742 seems to be similar

### 🛡️ Security Policy

- [x] I have read and agree to Uptime Kuma's [Security Policy](https://github.com/louislam/uptime-kuma/security/policy).

### 📝 Description

Since the v2 bump (I guess), the push monitor behavior changed in a way that I am not able to explicitly push a down status anymore.
Before, pushing with `?status=down&msg=fail` in the URL explicitly put the monitor status to Down (red). Now, it simply put my monitor in Pending (Orange).
I expect to obtain this pending state only in a missing heartbeat case, not when I explicitly push a down status.

### 👟 Reproduction steps

1. Configure a push monitor with an heartbeat interval and retry interval, and a retries value of (let's say) 6.
2. Push with curl an explicit down status (e.g. `?status=down&msg=fail`)
3. Notice that the monitor is in pending state and not down state as expected

### 👀 Expected behavior

Pushing a down state should put the monitor in down state in any case.

### 😓 Actual Behavior

Pushing a down state put the monitor in pending state.

### 🐻 Uptime-Kuma Version

2.0.2

### 💻 Operating System and Arch

Debian (with docker compose stack with official image)

### 🌐 Browser

Safari

### 🖥️ Deployment Environment

- **Runtime Environment**:
  - Docker: Version `27.5.1, build 9f9e405
  - Docker Compose: Version `v2.32.4`
- **Database**:
  - SQLite: Embedded
- **Database Storage**:
  - **Filesystem**:
    - Linux: ext4
  - **Storage Medium**: SSD
- **Uptime Kuma Setup**:
  - Number of monitors: `50`

### 📝 Relevant log output

```bash session

```

### PR DESCRIPTION
**Pull request by eureka0928**
<sub>ℹ️ To keep reviews fast and effective, please make sure you’ve [read our pull request guidelines](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma)</sub>

## 📝 Summary of changes done and why they are done

- Explicitly pushing `status=down` now bypasses retry logic and goes directly to DOWN

## Problem

When a user explicitly pushes `status=down` to a push monitor with retries configured, the monitor incorrectly goes to PENDING instead of DOWN. Users expect that explicitly pushing down should immediately mark the monitor as DOWN.

**Reproduction:**
1. Create push monitor with `Retries = 3`
2. Push `status=down` explicitly: `curl "http://localhost:3001/api/push/TOKEN?status=down"`
3. **Bug:** Monitor goes to PENDING (not DOWN)

## Root Cause

The `determineStatus()` function applies retry logic to all DOWN statuses, regardless of whether the status was explicitly provided by the user or resulted from a timeout/missed push.

## Solution

Added `isExplicitDown` flag that bypasses retry logic when `status=down` is explicitly pushed:

```javascript
// Detect explicit down push
const isExplicitDown = request.query.status === "down";

// In determineStatus(): bypass retry logic
if (isExplicitDown && status === DOWN) {
    bean.retries = 0;
    bean.status = DOWN;
    return;
}
```

## Behavior Changes

| Scenario | Before | After |
|----------|--------|-------|
| Push `status=down` with retries | PENDING | DOWN |
| Timeout/missed push with retries | PENDING | PENDING (unchanged) |

## 📋 Related issues

- Relates to #6406 
- Resolves #6406

## 📄 Checklist

<details>
<summary>Please follow this checklist to avoid unnecessary back and forth (click to expand)</summary>

- [ ] ⚠️ If there are Breaking change (a fix or feature that alters existing functionality in a way that could cause issues) I have called them out
- [ ] 🧠 I have disclosed any use of LLMs/AI in this contribution and reviewed all generated content.
      I understand that I am responsible for and able to explain every line of code I submit.
- [ ] 🔍 My code adheres to the style guidelines of this project.
- [ ] ⚠️ My changes generate no new warnings.
- [ ] 🛠️ I have reviewed and tested my code.
- [ ] 📝 I have commented my code, especially in hard-to-understand areas (e.g., using JSDoc for methods).
- [ ] 🤖 I added or updated automated tests where appropriate.
- [ ] 📄 Documentation updates are included (if applicable).
- [ ] 🔒 I have considered potential security impacts and mitigated risks.
- [ ] 🧰 Dependency updates are listed and explained.

</details>

## 📷 Screenshots or Visual Changes

- **UI Modifications**: Highlight any changes made to the user interface.
- **Before & After**: Include screenshots or comparisons (if applicable).

### CODE REVIEW

**Comment by fury0928** [comment]
@CommanderStorm would you review this PR as well? for two issues fix

File: server/model/monitor.js [hunk 1]
```diff
@@ -1294,7 +1294,7 @@ class Monitor extends BeanModel {
         // UP -> UP = not important
         // PENDING -> PENDING = not important
         // * PENDING -> DOWN = important
-        // PENDING -> UP = not important
+        // * PENDING -> UP = important (recovery from potential trouble)
```
Comment (CommanderStorm) [inline server/model/monitor.js]: I don't think this does not fix the issue precicely.
It creates the exact same problem, but on the over-alerting side.

This will alert on the folling series (UP, PENDING, UP) and (UP, DOWN, PENDING, UP).
We only want the later to alert sadly, so it is more complicated.

File: server/routers/api-router.js [hunk 2]
```diff
@@ -586,13 +590,21 @@ router.get("/api/badge/:id/response", cache("5 minutes"), async (request, respon
  * @param {number} maxretries - The maximum number of retries allowed.
  * @param {boolean} isUpsideDown - Indicates if the monitor is upside down.
  * @param {object} bean - The new heartbeat object.
+ * @param {boolean} isExplicitDown - If status=down was explicitly pushed, bypass retries.
  * @returns {void}
  */
-function determineStatus(status, previousHeartbeat, maxretries, isUpsideDown, bean) {
+function determineStatus(status, previousHeartbeat, maxretries, isUpsideDown, bean, isExplicitDown = false) {
```
Comment (CommanderStorm) [inline server/routers/api-router.js]: this only has one caller

```suggestion
function determineStatus(status, previousHeartbeat, maxretries, isUpsideDown, bean, isExplicitDown) {
```

File: server/routers/api-router.js [hunk 3]
```diff
@@ -586,13 +590,21 @@ router.get("/api/badge/:id/response", cache("5 minutes"), async (request, respon
...
     if (isUpsideDown) {
         status = flipStatus(status);
     }
 
+    // If status=down was explicitly pushed, bypass retry logic and go directly to DOWN
+    if (isExplicitDown && status === DOWN) {
+        bean.retries = 0;
+        bean.status = DOWN;
+        return;
+    }
```
Comment (CommanderStorm) [inline server/routers/api-router.js:636]: Yes, this is what we should do.

Thing is, is this a breaking change?
Since people pushing down and then depending on retries (which were default=1 pre `v2.0`), I think I would like to defer this change to `v3.0` (which is not that far off)

**Comment by fury0928** [comment]
@CommanderStorm this is splitted into one PR

File: server/model/monitor.js [hunk 4]
```diff
@@ -1294,7 +1294,6 @@ class Monitor extends BeanModel {
         // UP -> UP = not important
         // PENDING -> PENDING = not important
         // * PENDING -> DOWN = important
```
Comment (CommanderStorm) [inline server/model/monitor.js:1469]:
```suggestion
        // * PENDING -> DOWN = important
        // * PENDING -> UP = not important
```

File: server/routers/api-router.js (hunk 2 above)
Comment (CommanderStorm) [inline server/routers/api-router.js]:
```suggestion
function determineStatus(status, previousHeartbeat, maxretries, isUpsideDown, bean, isExplicitDown) {
```

**Comment by fury0928** [comment]
Hi @CommanderStorm  when would you launch the v3.0? 😉

**Comment by CommanderStorm** [comment]
This will take a while. If you want, you can revise it onto the v3.0 branch and we can merge it there

**Comment by dallyger** [comment]
Is there a way to opt back in to explicitly push a pending status? Something like a `status=pending` or `status=retry` query parameter.

We currently use the DOWN status with retries to differ between "command did not run" and "command ran but was not successful" while keeping the time metric of those failed runs.
Those would be lost if we skip the ping. Marking the status as DOWN directly is not preferred, as the commands are allowed to fail sometimes as long as they run again soon.

One such use case is a command where I monitor disk space capacity of a server to warn on usage above e.g. 80% where I misuse the time metric as the disk usage percentage. Graph shows 0-100ms but means 0-100% disk used.
Not pushing the "pending" status means, that I don't know how rapidly it is filling up after reaching the threshold. Pushing it as DOWN immediately will trigger a lot of notifications if it fluctuates between 79-80%.

**Comment by CommanderStorm** [comment]
> Is there a way to opt back in to explicitly push a pending status? Something like a `status=pending` or `status=retry` query parameter.

Yes, if you push `status=pending` this would not change this.
You still will retry as usual as far as I think

PS: I know this is a breaking change for you, I still want to give the ability to fail the check instead of having basically 2x pending (one named "pending", one named "down") for the monitor.
This change is a while out, as I will only merge it into v3.0

**Comment by dallyger** [comment]
> Yes, if you push status=pending this would not change this.

Awesome, that is all I need.

> PS: I know this is a breaking change for you

No worries. As long as it is clearly communicated, I see no issues with that. A fix on my end is easy and can be applied even before upgrading to the v3.0.

I do prefer the difference between `state=pending` and `state=down` too! In fact, this is what I suggested in <https://github.com/louislam/uptime-kuma/issues/3208>, which resulted in the DOWN state to respect the retries:

> I think the best action would be to add a third state (up, down and pending)

I also saw this issue while searching for mine: <https://github.com/louislam/uptime-kuma/issues/4785>.  
So maybe even a fourth status could be added?
My initial idea would be to explicitly allow these states:

`up` - Mark monitor as up.
`down` - Mark monitor as down ignoring retries.
`retry` - Mark monitor as pending (or keep it DOWN) as it will be retried later on
`pending` - Do not change monitor status but add metrics / message to the history.

Alternatively the `pending` could keep UP as UP but move DOWN to PENDING. Not sure which behavior I would prefer. Does it cause notifications if it then goes back to DOWN? Is this maybe even preferred?

**Comment by CommanderStorm** [comment]
> can be applied even before upgrading to the v3.0.

Breaking changes, no matter how nice, need to be done in a semver major.
We loose all trust otherwise

**Comment by CommanderStorm** [comment]
> So maybe even a fourth status could be added?

Introducing a fith status (no matter if it is partial, retrying or whatever) would involve a fairly large amount of work, as most of our internal code and notification providers aren’t currently designed with this in mind. Supporting it properly would require changes across multiple areas.

Given my current review capacity, I’m unfortunately not able to take on or oversee additional work of this scope right now.

For some additional background and context, please see:
- #6260 

There are also some larger refactorings (for example starting to increase our test coverage) needed in how our internal components interact before we could realistically consider something like this.
Currently, the risk of such a change is way too high.
If you want to contribute to the effort of reducing such a risk, I can mentor/ guide you towards this goal

**Comment by fury0928** [comment]
Hi @CommanderStorm 
Hope you're having a good weekend

I'd like to reopen this when you release the 3.0.0 or is there any way to merge quickly?
Thank you

**Comment by CommanderStorm** [comment]
If you rebase onto the V3 branch, we can merge there as said

**Comment by fury0928** [comment]
> If you rebase onto the V3 branch, we can merge there as said

Awesome, let me do on monday
Have a nice weekend!

**Comment by CommanderStorm** [comment]
I don't think this is quite rebased s there still is a merge conflict

**Comment by fury0928** [comment]
`.github/workflows/auto-test.yml` and `server/model/rdap-dns.json` — pre-existing formatting issues on the 3.0.X branch, not related to our changes.    
cc: @CommanderStorm 

Ready for review

File: server/model/monitor.js [hunk 5]
```diff
@@ -1432,7 +1432,7 @@ class Monitor extends BeanModel {
...
-        // PENDING -> UP = not important
+        // * PENDING -> UP = important
```
Comment (CommanderStorm) [inline server/model/monitor.js]: I don't think this is an intentional change, right?


```suggestion
        // PENDING -> UP = not important
```

**Comment by CommanderStorm** [comment]
Please fix the unrelated formatting changes too.
having a green build is fairly important

**Comment by CommanderStorm** [comment]
not sure how they went in in the first place

**Comment by fury0928** [comment]
Hi @CommanderStorm this is ready to go
