### PR TITLE
Fix Slack notifications when URL is present

### LINKED ISSUE #4864: Slack notifications fail when url is partially defined
### 📑 I have found these related issues/pull requests

None found.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Slack notifications fail if a monitorJSON.url is partially defined - ex, `https://`.

The error is coming from the "visit website" button that was recently added - if the url is incomplete, Slack will not allow the message.

### 👟 Reproduction steps

1. Create a slack alert
2. Create a DNS monitor, TXT, anything valid
3. Save the monitor
4. Edit the monitor to an invalid dns record
    - NOTE: it appears that editing the monitor is what actually populates the `.url` field, so editing is important. This step also causes the alert to trigger. 
6. Observe error in logs

Note that I added a `console.log('monitor URL'...` in `slack.js` `buildActions`:

```js
    static buildActions(baseURL, monitorJSON) {
        const actions = [];

        if (baseURL) {
            actions.push({
                "type": "button",
                "text": {
                    "type": "plain_text",
                    "text": "Visit Uptime Kuma",
                },
                "value": "Uptime-Kuma",
                "url": baseURL + getMonitorRelativeURL(monitorJSON.id),
            });

        }

        console.log("Monitor URL: ", monitorJSON.url);

        if (monitorJSON.url) {
            actions.push({
                "type": "button",
                "text": {
                    "type": "plain_text",
                    "text": "Visit site",
                },
                "value": "Site",
                "url": monitorJSON.url,
            });
        }

        return actions;
    }
```

### 👀 Expected behavior

Slack alert is sent

### 😓 Actual Behavior

Alert is not sent.

### 🐻 Uptime-Kuma Version

master branch (tested on 1.23.13 to NOT be a problem)

### 💻 Operating System and Arch

PopOS

### 🌐 Browser

Version 117.0.5938.132 (Official Build) (64-bit)

### 🖥️ Deployment Environment

- Runtime: v20.11.0
- Database: sqlite
- Filesystem used to store the database on: ext4
- number of monitors: 1

### 📝 Relevant log output

```shell
Monitor URL:  https://
2024-06-18T16:45:47-04:00 [MONITOR] ERROR: Cannot send notification to My Slack Alert (1)
2024-06-18T16:45:47-04:00 [MONITOR] ERROR: Error: Error: AxiosError: Request failed with status code 400 invalid_attachments
    at Slack.throwGeneralAxiosError (/home/bdavis/Dev/uptime-kuma/server/notification-providers/notification-provider.js:69:15)
    at Slack.send (/home/bdavis/Dev/uptime-kuma/server/notification-providers/slack.js:178:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Monitor.sendNotification (/home/bdavis/Dev/uptime-kuma/server/model/monitor.js:1349:21)
    at async beat (/home/bdavis/Dev/uptime-kuma/server/model/monitor.js:937:21)
    at async safeBeat (/home/bdavis/Dev/uptime-kuma/server/model/monitor.js:1023:17)
2024-06-18T16:45:47-04:00 [MONITOR] DEBUG: [asdf] apicache clear
2024-06-18T16:45:47-04:00 [MONITOR] WARN: Monitor #4 'asdf': Failing: queryTxt ENOTFOUND _remotef_acmfe-challenge.apisec.malteksolutions.com | Interval: 60 seconds | Type: dns | Down Count: 0 | Resend Interval: 0
2024-06-18T16:45:47-04:00 [UPTIME-CALC] DEBUG: Remove old data
```

### PR DESCRIPTION
**Pull request by Rudedog9d**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

- Sets URL to null if the current monitor type doesn't utilize the URL field
    - The URL will be saved and used by notifications later if it is not set to null on save
- Utilizes `getUrl` helper to set URL to `null` in monitorJSON if URL is invalid.

Fixes #4864 

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

`ftp://`, `steam://`, and `asdf://` url schemes all supported by Slack:

image

URL removed on save of DNS monitor: 

image

### CODE REVIEW

**Review by CommanderStorm — CHANGES_REQUESTED** [review]
Your change interacts with every notification provider we have.
This is a bit too risky for my taste.
Could you refactor the slack notification privider to use this function instead of using the url parameter?

https://github.com/louislam/uptime-kuma/blob/dc154437164f6ec1b89b8e9f60e1cecc64709a28/server/notification-providers/notification-provider.js#L22-L50

**Comment by Rudedog9d** [comment]
Oh yea that's perfect, thanks for pointing that out! I've updated the provider and removed the validation step. I did leave the change to update the produced JSON object though, let me know if that should be removed.

File: server/notification-providers/slack.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ class Slack extends NotificationProvider {
 
         }
 
-        if (monitorJSON.url) {
+        if (this.extractAdress(monitorJSON)) {
```
Comment (CommanderStorm) [inline server/notification-providers/slack.js:51]: the extracted `adress` should be used below instead of `monitorJSON.url`.

(I can't suggest this change because of github restrictions)

```suggestion
        const adress = this.extractAdress(monitorJSON);
        if (adress) {
```

File: server/model/monitor.js [hunk 2]
```diff
@@ -107,7 +107,7 @@ class Monitor extends BeanModel {
             pathName,
             parent: this.parent,
             childrenIDs: await Monitor.getAllChildrenIDs(this.id),
-            url: this.url,
+            url: this.getUrl()?.href,
```
Comment (CommanderStorm) [inline server/model/monitor.js:110]: lets not change this one.
As stated previously, I have not looked into the other notification providers/monitors and don't think that this issue needs to do this.
I am thinking about notification providers such as webhooks allowing templating or another monitor using this field for somethign which is not considered a url by node.

Without good looking into, this is too risky for me.

```suggestion
            url: this.url,
```

**Review by CommanderStorm — CHANGES_REQUESTED** [review]
I have left comments about the two areas below

File: server/notification-providers/slack.js (hunk 1 above)
Comment (Rudedog9d) [reply server/notification-providers/slack.js]: My bad :facepalm:

**Review by CommanderStorm — APPROVED** [review]
Thanks for the bugfix! 🎉 



> [!NOTE]
> This PR is part of the [`v2.0` merge window](https://github.com/louislam/uptime-kuma/milestone/24) => see #4500 for the bugs that need to be addressed before we can ship this release ^^

<sub>All changes in this PR are small and uncontroversial ⇒ merging with junior maintainer approval</sub>
