### PR TITLE
Attempt an OAuth2 Refresh on 401

### LINKED ISSUE #3902: OAuthToken Expiry Refresh Will Never Occur Where ‘Expires_at’ Is Not Provided
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Info:
The expires_at key is only labelled as 'recommended' and will not be provided in every openid-client response
https://datatracker.ietf.org/doc/html/rfc6749#section-4.2.2

For Salesforce, it is not provided.
https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_client_credentials_flow.htm&type=5

----

I began to notice many OAuth2 failures (401) which occurred on endpoints being monitored. They seemed to line up with the session expiry for the platform being monitored. I found that editing and hitting save on the monitor without actually changing anything resolved the issue (seemingly forced a refresh).

Looking into the `getOidcTokenClientCredentials` method from `util-server.js`, we never seem to refresh the OAuthToken. This is primarily due to no `expires_at` object key being provided. This is relied upon by monitor.js within the `this.auth_method === "oauth2-cc"` condition.

As a result of the above the following condition which allows a refresh is ONLY ever entered when `this.oauthAccessToken` is undefined, which happens to occur on save. This results in a failure until saving. (`monitor.js`)

image

### 👟 Reproduction steps

I found this to apply to Salesforce OAuth2 Client Credentials.

As all salesforce organisations are different, you can replicate this by first creating your Connected App in salesforce by following the recommended steps here https://help.salesforce.com/s/articleView?id=sf.connected_app_client_credentials_setup.htm&type=5.

1. Create a monitor for HTTP(s) [This can also be any of the extended HTTP(s) types]
2. Include your endpoint such as https://{your_domain}.my.salesforce.com/services/data/v57.0/limits
3. Configure the Authentication Method to OAuth2: Client Credentials
4. Here you can include debug logs for `this.oauthAccessToken` after it is set by `getOidcTokenClientCredentials` to see the `expires_at` missing OR wait for the session to expire (based on your organisation settings. 

### 👀 Expected behavior

The OAuth2 token is refreshed.

I believe we can handle this in a few ways:

- Call `getOidcTokenClientCredentials` after 401 when `this.auth_method === "oauth2-cc"`
- Set `this.oauthAccessToken` to undefined after 401 when `this.auth_method === "oauth2-cc"`
- Include a new session expiry time related field for the user to manually input the expected session life to be used for refreshing
- Hardcode some small number so it's refreshed for every request (if we really have to...)

### 😓 Actual Behavior

I received a down alert

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Windows 11 x64

### 🌐 Browser

Google Chrome 118.0.5993.70

### 🐋 Docker Version

_No response_

### 🟩 NodeJS Version

18.17.1

### 📝 Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by HdroguettA**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

Fixes #3902 

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

### CODE REVIEW

**Comment by louislam** [comment]
@hegerdes As I am not familiar with OAuth. Would you like to help to test it? Thanks.

**Comment by hegerdes** [comment]
Sure, I've got some time on the weekend and will look into it then.

But I will only comment about functionally, there seem to be some extra changes like moving code to an extra method (which I'm fine with) and renaming vars. It's your project and you have to decide about style.

File: server/model/monitor.js [hunk 1]
```diff
@@ -1018,18 +1016,35 @@ class Monitor extends BeanModel {
...
+            if (this.auth_method === "oauth2-cc" && error.response.status === 401 && !options.isReattempt) {
+                this.oauthAccessToken = await this.makeOidcTokenClientCredentialsRequest();
+                let oauth2AuthHeader = {
+                    "Authorization": this.oauthAccessToken.token_type + " " + this.oauthAccessToken.access_token,
+                };
+                options.headers = { ...(options.headers),
+                    ...(oauth2AuthHeader)
+                };
+                options.isReattempt = true;
+                return this.makeAxiosRequest(options, true);
```
Comment (hegerdes) [inline server/model/monitor.js:1034]: It works but I would't use `isReattempt` here because uptime-kuma already has a built in logic for this. See line 1039 with `!finalCall` in the if statement. Yours works the the same but is an additional method of archiving the same thing,

File: server/model/monitor.js [hunk 2]
```diff
@@ -1018,18 +1016,35 @@ class Monitor extends BeanModel {
...
             return res;
-        } catch (e) {
+        } catch (error) {
+
+            /**
+             * Make a single attempt to obtain an new access token in the event that
+             * the recent api request failed for authentication purposes
+             */
+            if (this.auth_method === "oauth2-cc" && error.response.status === 401 && !options.isReattempt) {
+                this.oauthAccessToken = await this.makeOidcTokenClientCredentialsRequest();
```
Comment (hegerdes) [inline server/model/monitor.js:1026]: For information purposes I would add a debug log line stating that there will be an internal retry with a new token. But it is not really needed.

File: server/model/monitor.js [hunk 3]
```diff
@@ -1532,6 +1547,23 @@ class Monitor extends BeanModel {
...
+     * Obtains a new Oidc Token
+     * @returns {Promise<object>} OAuthProvider client
+     */
+    async makeOidcTokenClientCredentialsRequest() {
+        log.debug("monitor", `[${this.name}] The oauth access-token undefined or expired. Requesting a new one`);
+        const oAuthAccessToken = await getOidcTokenClientCredentials(this.oauth_token_url, this.oauth_client_id, this.oauth_client_secret, this.oauth_scopes, this.oauth_auth_method);
+        if (this.oauthAccessToken?.expires_at) {
+            log.debug("monitor", `[${this.name}] Obtained oauth access-token. Expires at ${new Date(this.oauthAccessToken?.expires_at * 1000)}`);
+        } else {
+            log.debug("monitor", `[${this.name}] Obtained oauth access-token. Time until expiry was not provided`);
```
Comment (hegerdes) [inline server/model/monitor.js:1561]: Just a personal request on my side: If I would do the whole OAuth implementation again I would add a default expiry time of 30min - just in case it is not provided by the Issuer or if the website to monitor does not return the right HTTP status code (401). This might catch some additional future edge cases.

**Review by hegerdes — APPROVED** [review]
The code works as expected - so 👍 from me.

I still added some thoughts of mine. Aside from the `finalCall` thing I wouldn't really suggest any needed changes.

Thanks for the PR.

File: server/model/monitor.js (hunk 1 above)
Comment (HdroguettA) [reply server/model/monitor.js:1034]: Absolutely, resolved in the next commit

File: server/model/monitor.js (hunk 2 above)
Comment (HdroguettA) [reply server/model/monitor.js:1026]: This occurs in the first line of the makeOidcTokenClientCredentialsRequest method

**Review by hegerdes — APPROVED** [review]
Looks good 👍
