### PR TITLE
fix(dashboard): add scroll bar to tags dropdown

### LINKED ISSUE #6885: Tags dropdown menu lacks scrollbar, preventing selection of more tags
### 📑 I have found these related issues/pull requests

N/A

### 🔖 Feature description

In the tag dropdown menu on the dashboard, if there are too many tags to fit within the screen area, the additional tags will not be displayed and cannot be selected (see image below)

Image

### ✔️ Solution

Perhaps a scroll bar could be added to the tags dropdown menu to allow users to browse tags that are not displayed at the bottom.

### ❓ Alternatives

If the scrollbar conflicts with the list of monitors, alternatively consider a multi-column layout to display all tags fully on the current screen (the number of tags shouldn't be so large that they don't even fit on a single screen).

### 📝 Additional Context

N/A

### PR DESCRIPTION
**Pull request by smartcoder0777**
Fixed: https://github.com/louislam/uptime-kuma/issues/6885

# Summary

In this pull request, the following changes are made:

A scrollbar was added to the Tags filter dropdown on the dashboard so that when there are many tags, the list is scrollable (max-height min(50vh, 320px) with overflow-y: auto) and all tags can be selected. The Status dropdown is unchanged.

- Relates to #issue-number 
- Resolves #6885

<details>
<summary>Please follow this checklist to avoid unnecessary back and forth (click to expand)</summary>

- [ ] ⚠️ If there are Breaking change (a fix or feature that alters existing functionality in a way that could cause issues) I have called them out
- [ ] 🧠 I have disclosed any use of LLMs/AI in this contribution and reviewed all generated content.
      I understand that I am responsible for and able to explain every line of code I submit.
- [x] 🔍 Any UI changes adhere to visual style of this project.
- [x] 🛠️ I have self-reviewed and self-tested my code to ensure it works as expected.
- [ ] 📝 I have commented my code, especially in hard-to-understand areas (e.g., using JSDoc for methods).
- [ ] 🤖 I added or updated automated tests where appropriate.
- [ ] 📄 Documentation updates are included (if applicable).
- [ ] 🧰 Dependency updates are listed and explained.
- [x] ⚠️ CI passes and is green.

</details>

## Screenshots for Visual Changes

- **UI Modifications**: Highlight any changes made to the user interface.
- **Before & After**: Include screenshots or comparisons (if applicable).

| Event              | Before                | After                |
| ------------------ | --------------------- | -------------------- |
| `UP`               | image |image |
| `DOWN`             | Before | After |
| Certificate-expiry | Before | After |
| Testing            | Before | After |

Contribution by Gittensor, see my contribution statistics at https://gittensor.io/miners/details?githubId=191128130

### CODE REVIEW

**Comment by smartcoder0777** [comment]
Could a maintainer please rename this to fix(dashboard): add scrollbar to tags dropdown when many tags? I don’t have permission to edit the title.

**Comment by smartcoder0777** [comment]
@CommanderStorm Thanks!

File: src/components/MonitorListFilter.vue [hunk 1]
```diff
@@ -343,4 +349,22 @@ export default {
 .btn-collapse-all {
     transition: none !important;
 }
+
+/* Scrollable tags dropdown (issue #6885) */
```
Comment (CommanderStorm) [inline src/components/MonitorListFilter.vue]:
```suggestion
```

File: src/components/MonitorListFilter.vue [hunk 2]
```diff
@@ -117,22 +117,28 @@
...
-                        </span>
-                    </div>
-                </div>
-            </li>
-            <li v-if="tagsList.length === 0">
-                <div class="dropdown-item disabled px-3">
-                    {{ $t("No tags found.") }}
+            <li class="tags-dropdown-scroll-wrapper">
+                <div class="tags-dropdown-scroll">
+                    <ul class="tags-dropdown-list">
```
Comment (CommanderStorm) [inline src/components/MonitorListFilter.vue]:
```suggestion
            <li class="list-unstyled m-0 p-0">
                <div class="tags-dropdown-scroll overflow-y-auto">
                    <ul class="list-unstyled m-0 p-0">
```

File: src/components/MonitorListFilter.vue [hunk 3]
```diff
@@ -343,4 +349,21 @@ export default {
...
+.tags-dropdown-scroll {
+    max-height: min(50vh, 320px);
+    overflow-y: auto;
+}
+
+.tags-dropdown-list {
+    list-style: none;
+    padding: 0;
+    margin: 0;
+}
```
Comment (CommanderStorm) [inline src/components/MonitorListFilter.vue]:
```suggestion
.tags-dropdown-scroll {
    max-height: min(50vh, 320px);
}
```

File: src/components/MonitorListFilter.vue [hunk 4]
```diff
@@ -343,4 +349,8 @@ export default {
 .btn-collapse-all {
     transition: none !important;
 }
+
+.tags-dropdown-scroll {
+    max-height: min(50vh, 320px);
```
Comment (CommanderStorm) [inline src/components/MonitorListFilter.vue:354]:
```suggestion
    max-height: min(50vh, 320px);
    overflow-y: auto;
```

File: src/components/MonitorListFilter.vue [hunk 5]
```diff
@@ -117,22 +117,28 @@
...
-                            </span>
-                        </span>
-                    </div>
-                </div>
-            </li>
-            <li v-if="tagsList.length === 0">
-                <div class="dropdown-item disabled px-3">
-                    {{ $t("No tags found.") }}
+            <li class="list-unstyled m-0 p-0">
+                <div class="tags-dropdown-scroll overflow-y-auto">
```
Comment (CommanderStorm) [inline src/components/MonitorListFilter.vue]:
```suggestion
                <div class="tags-dropdown-scroll">
```
