### PR TITLE
fix: noisy domain expiry checks in monitor editor and missing debuggability

### LINKED ISSUE #6633: Domain expiry monitor is very chatty and logs too much
### 📑 I have found these related issues/pull requests

None

### 🛡️ Security Policy

- [x] I have read and agree to Uptime Kuma's [Security Policy](https://github.com/louislam/uptime-kuma/security/policy).

### 📝 Description

We have a domain expiry montor.
This monitor does not support all top level domains like for example .de because DENIC has not rolled out their RDAP endpoint (they have, it is just in stealth mode).

What happens is that on every input, we check if this is a valdid URL and may.
The original intent behind this was to disable the domain expiry checkbox if thi checkbox does not make sense.

First of all, the checkbox just gets set to false, not disabled (Bug 1), but also these checks cause unnessesary log spam as reported by @iotux below

### 👟 Reproduction steps

> I am not sure why for you there are all of thee entries, did you create a new monitor or have to save for each line

To clarify a bit.
The 'null' entries are from several monitors where I have used IP addresses.
For the '.st', it is actually a domain name I own.
For the others, I am not saving the entries. For each and every character entered in the input field, a log line is written

as reported by @iotux 

### 👀 Expected behavior

- Not be so incredibly spammy
- disable this option instead of falsifying it when it does not make sense

### 😓 Actual Behavior

```
2026-01-07T04:00:31+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.u' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:31+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.un' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:31+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.unu' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:32+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.null' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:32+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.null' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:32+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.unus' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:32+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.unusu' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:33+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.unusua' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:33+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.unusual' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:34+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.st' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:35+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.unusual' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:35+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.s' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:36+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.su' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:36+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.null' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:36+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.null' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:36+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.sub' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:37+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.sub' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:37+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.null' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:37+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.d' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:37+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.null' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:38+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.null' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:38+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.null' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:38+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.do' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:39+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.dom' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:39+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.null' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:39+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.doma' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:39+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.domai' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:40+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.domain' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:41+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.domain' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:42+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.n' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:00:44+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.nam' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:01:32+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.null' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:01:32+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.null' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:01:34+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.st' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:01:35+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.null' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:01:35+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.null' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:01:37+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.null' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:01:37+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.null' because its RDAP endpoint is not listed in the IANA database.
2026-01-07T04:01:38+01:00 [DOMAIN_EXPIRY] WARN: Domain expiry unsupported for '.null' because its RDAP endpoint is not listed in the IANA database.
```

### 🐻 Uptime-Kuma Version

v2.1 dev branch

### 💻 Operating System and Arch

unclear

### 🌐 Browser

irrelevant

### 🖥️ Deployment Environment

was not reported

### 📝 Relevant log output

```bash session

```

### PR DESCRIPTION
**Pull request by josephadamsdev**
While typing the URL/hostname in the monitor editor, the frontend was calling `checkMointor` on every keystroke. That could spam the server log with domain expiry warnings, and it also kept turning off the “Domain Name Expiry Notification” option.

This PR debounces that check, keeps the toggle visible but disabled until a supported domain is detected, and avoids warn-level logging for incomplete/invalid inputs during the editor check.

Fixes #6633
Fixes https://github.com/louislam/uptime-kuma/issues/6639

Testing:
- `npm run lint:js`
- `npm run lint:style`
- `node --test --test-reporter=spec test/backend-test/test-domain.js`

Contribution by Gittensor, see my contribution statistics at https://gittensor.io/miners/details?githubId=105917501

### CODE REVIEW

**Comment by crackedsdev** [comment]
@CommanderStorm  Hope this solve the issue ?

File: src/pages/EditMonitor.vue
Comment (CommanderStorm) [inline src/pages/EditMonitor.vue]: could we add a small helptext here that shows if `!hasDomain` and additionally communicates `"RDAP not supported for top level domain"`?

File: src/pages/EditMonitor.vue [hunk 1]
```diff
@@ -1795,12 +1807,20 @@ message HealthCheckResponse {
         },
 
         "monitorTypeUrlHost"(data) {
-            this.$root.getSocket().emit("checkMointor", data, (res) => {
-                this.hasDomain = !!res?.domain;
-                if (!res?.domain) {
-                    this.monitor.domainExpiryNotification = false;
-                }
-            });
+            if (this.checkMonitorDebounce != null) {
```
Comment (CommanderStorm) [inline src/pages/EditMonitor.vue:1813]: Nice call on thinking about this 👍🏻

File: server/model/domain_expiry.js [hunk 2]
```diff
@@ -148,10 +148,26 @@ class DomainExpiry extends BeanModel {
         if (excludeTypes.includes(m.type) || m.type?.match(/sql$/)) {
             return false;
         }
-        const tld = parseTld(urlTypes.includes(m.type) ? m.url : m.type === "grpc-keyword" ? m.grpcUrl : m.hostname);
+
+        const target = urlTypes.includes(m.type) ? m.url : m.type === "grpc-keyword" ? m.grpcUrl : m.hostname;
```
Comment (CommanderStorm) [inline server/model/domain_expiry.js]: I have no clue what this means or how it behaves.
Could we either add brachets or (preferably) not net ternaries?

I am aware that you have fixed it 95%, but lets fix it 100% ^^

File: src/pages/EditMonitor.vue [hunk 3]
```diff
@@ -1517,6 +1518,17 @@ export default {
             };
         },
 
+        showDomainExpiryNotification() {
+            const excludedTypes = [ "docker", "group", "push", "manual", "rabbitmq", "redis" ];
```
Comment (CommanderStorm) [inline src/pages/EditMonitor.vue:1525]: please add a code commet below this and its equivalent in the backend that these need adjusting together.

This way we won't have as much confusion once this is updated someday

**Review by CommanderStorm — COMMENTED** [review]
Works nicely and looks good to me.
I have two nits/minor comments, but nothing major.

**Comment by crackedsdev** [comment]
@CommanderStorm  Thanks for the review I pushed a follow-up that addresses the nits:

- Added a small help text under the checkbox when domain expiry can’t be enabled (including the “RDAP not supported for this TLD” case).
- Refactored the backend target selection/support check to avoid nested ternaries.
- Added a note to keep the frontend/backend type filters in sync.

Let me know if there's anything i can add

**Review by CommanderStorm — APPROVED** [review]
Nice work, thank you.
This will greatly improve how people can debug this!

I added a few more translations, nothing special

File: server/model/monitor.js [hunk 4]
```diff
@@ -920,14 +920,15 @@ class Monitor extends BeanModel {
 
             if (bean.status !== MAINTENANCE && Boolean(this.domainExpiryNotification)) {
                 try {
-                    const domainExpiryDate = await DomainExpiry.checkExpiry(this);
+                    const supportInfo = await DomainExpiry.checkSupport(monitor);
```
Comment (CommanderStorm) [inline server/model/monitor.js]:
```suggestion
                    const supportInfo = await DomainExpiry.checkSupport(this);
```

File: server/model/monitor.js [hunk 5]
```diff
@@ -1232,7 +1233,7 @@ class Monitor extends BeanModel {
     static async sendDomainInfo(io, monitorID, userID) {
         const monitor = await R.findOne("monitor", "id = ?", [ monitorID ]);
 
-        const domain = await DomainExpiry.forMonitor(monitor);
+        const domain = await DomainExpiry.findByDomainNameOrCreate(monitor);
         if (domain?.expiry) {
             io.to(userID).emit("domainInfo", monitorID, domain.daysRemaining, new Date(domain.expiry));
         }
```
Comment (CommanderStorm) [inline server/model/monitor.js]:
```suggestion
        try {
            const supportInfo = await DomainExpiry.checkSupport(monitor);
            const domain = await DomainExpiry.findByDomainNameOrCreate(supportInfo.domain);
            if (domain?.expiry) {
                io.to(userID).emit("domainInfo", monitorID, domain.daysRemaining, new Date(domain.expiry));
            }
        } catch (e){}
```

**Comment by iotux** [comment]
> two more cases that I missed

100% sounds good, but here are some possible improvements.

The  "if (!tld.publicSuffix)" filter in line 175 gladly slips through local domain names proviced by mDNS (frequently used in IoT environments), /etc/hosts or split local horizon DNS config.

To prevent un-needed "getRdapServer()" lookups, the (!tld.publicSuffix) should probably be replaced by (tld.isIcann), which effectively stops those local domain names to travel any further. Doing this will make it 110% ;-)
It may even be sufficient with only (!tld.isIcann) to filter out the others

See examples:
```
tld: {
  domain: null,
  domainWithoutSuffix: null,
  hostname: '10.11.1.60',
  isIcann: null,
  isIp: true,
  isPrivate: null,
  publicSuffix: null,
  subdomain: null
}
tld: {
  domain: 'esp32-sensor.local',
  domainWithoutSuffix: 'esp32-sensor',
  hostname: 'esp32-sensor.local',
  isIcann: false,
  isIp: false,
  isPrivate: false,
  publicSuffix: 'local',
  subdomain: ''
}
tld {
  domain: 'münchen.com',
  domainWithoutSuffix: 'münchen',
  hostname: 'münchen.com',
  isIcann: true,
  isIp: false,
  isPrivate: false,
  publicSuffix: 'com',
  subdomain: ''
}
```

Here is another 2%
```
const excludeTypes = [ "docker", "group", "push", "manual", "rabbitmq", "redis" ];
```
Should b:
```
const excludeTypes = [ "docker", "group", "push", "manual", "rabbitmq", "redis", "system-service" ];
```

**Comment by danielgoepp** [comment]
@CommanderStorm Thanks!

**Comment by CommanderStorm** [comment]
@danielgoepp thank **YOU** for testing our betas. Very few do that 😓

**Comment by Thomas-Ganter** [comment]
Now ... why is my log still flooded with domain expiry not being available messages?
image

I see there is a help text, and I see the checkbox is disabled  ... but it is checked and disabled, so I cannot uncheck it. 
image

Do I need to just "live with the warnings"?

**Comment by CommanderStorm** [comment]
@Thomas-Ganter  what version are you on? Are you on a version that includes this patch?

**Comment by CommanderStorm** [comment]
note that both .de and .ga are stealth RDAP servers.
They exist, but have not been published to IANA.

Please consider writing a mail to your registrar asking them to publish their rdap server.

**Comment by Thomas-Ganter** [comment]
> @Thomas-Ganter what version are you on? Are you on a version that includes this patch?

Just upgraded to 2.1.0. 
Is that patch not included there ... (sorry, did not check  ..  this was the first hit I found looking for the solution of my issue)

**Comment by CommanderStorm** [comment]
If you want, you can upgrade again to our latest or next (?) nightly.
You want this PR:

- https://github.com/louislam/uptime-kuma/pull/6884
