### PR TITLE
fix: remove modal when navigating back

### LINKED ISSUE #5008: dashboard: modal not removed when navigating back
### 📑 I have found these related issues/pull requests

I did look but didn't find anything.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The modal window is not fully cleaned up / removed when navigating back (via the browser navigation buttons). There is some logic to clean it up, as the dialog disappears.

### 👟 Reproduction steps

Navigate to the dashboard and click "Edit" on any entry.

image

Click something like "Setup Proxy".

image

Navigate back via the browser and observe the window is dark and nothing is clickable.

image

### 👀 Expected behavior

The modal and dialog should be cleared fully.

### 😓 Actual Behavior

The modal hangs around and renders the page unusable until refreshed.

### 🐻 Uptime-Kuma Version

1.23.13? I think?

### 💻 Operating System and Arch

N/A

### 🌐 Browser

Firefox (Linux)

### 🖥️ Deployment Environment

N/A - this is the demo site

### 📝 Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mohit-nagaraj**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

Fixes #5008 

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- User interface (UI)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [x] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

https://github.com/user-attachments/assets/f6dc99ac-5727-4143-90b8-bf105ccf3a7e

### CODE REVIEW

**Comment by mohit-nagaraj** [comment]
Do let me kno if other pop ups also needs these life cycle events to be implemented

File: src/components/CreateGroupDialog.vue [hunk 1]
```diff
@@ -33,15 +33,27 @@
...
     emits: [ "added" ],
     data: () => ({
         modal: null,
         groupName: null,
     }),
+    watch: {
+        $route(to, from) {
+            this.cleanupModal();
+        }
+    },
```
Comment (CommanderStorm) [inline src/components/CreateGroupDialog.vue:50]: is this not redundant to `beforeRouteLeave`?

```suggestion
```

File: src/components/CreateGroupDialog.vue [hunk 2]
```diff
@@ -33,15 +33,27 @@
 import { Modal } from "bootstrap";
 
 export default {
+    beforeRouteLeave(to, from, next) {
```
Comment (CommanderStorm) [inline src/components/CreateGroupDialog.vue:36]: are there cases where the `beforeUnmount` is not called?
If yes, please add a comment what this case is.
If no, lets remove this check and inline `cleanupModal` into `beforeUnmount`

File: src/components/CreateGroupDialog.vue [hunk 3]
```diff
@@ -58,6 +70,22 @@ export default {
...
+            if (this.modal) {
+                try {
+                    this.modal.hide();
+                } catch (e) {
+                    console.warn("Modal hide failed:", e);
+                }
+            }
+            document.body.classList.remove("modal-open");
+            document.body.style.paddingRight = "";
+            document.body.style.overflow = "";
```
Comment (CommanderStorm) [inline src/components/CreateGroupDialog.vue:87]: as far as I see these are already removed by `this.modal.hide()`.
Is there a case where you needed them which I am missing?

```suggestion
```

**Review by CommanderStorm — CHANGES_REQUESTED** [review]
Thanks for the PR,

I have left a few questions below, mostly regarding a bit of likely code-duplication.

File: src/components/CreateGroupDialog.vue (hunk 3 above)
Comment (mohit-nagaraj) [reply src/components/CreateGroupDialog.vue:87]: nope it wasnt actually removing those details, so thought to manually remove them

File: src/components/CreateGroupDialog.vue (hunk 2 above)
Comment (mohit-nagaraj) [reply src/components/CreateGroupDialog.vue:36]: If the user refreshes the page or navigates to another URL using the browser's address bar, the Vue instance might not clean up properly, meaning beforeUnmount won't be triggered. correct me if i am wrong

File: src/components/CreateGroupDialog.vue (hunk 1 above)
Comment (mohit-nagaraj) [reply src/components/CreateGroupDialog.vue:50]: hmm yea i was trying out both ways seeing which one worked then just left both off them there. beforeRouteLeave should handle the modal cleanup during route transitions then will remove any other redundant code

File: src/components/CreateGroupDialog.vue (hunk 3 above)
Comment (mohit-nagaraj) [reply src/components/CreateGroupDialog.vue:87]: nvm now tht i removed them still its working properly now too :)

File: src/components/CreateGroupDialog.vue (hunk 2 above)
Comment (mohit-nagaraj) [reply src/components/CreateGroupDialog.vue:36]: btw all of cleanupModal shud be made inline right if i am not wrong

**Comment by mohit-nagaraj** [comment]
> Feel too hacky and unsafe, as it's utilized dom and added a lot of events. I prefer not to change the current logic.

hey i have updated the code now, does this make it better.... i am just now relying on beforeUnmount hook to remove the modal

File: src/components/CreateGroupDialog.vue (hunk 2 above)
Comment (mohit-nagaraj) [reply src/components/CreateGroupDialog.vue]: hey so only one hook is calling the function cleanupModal, shud i make it inline? @CommanderStorm

**Comment by mohit-nagaraj** [comment]
@louislam could you re-review this once

**Comment by mohit-nagaraj** [comment]
@CommanderStorm

**Comment by mohit-nagaraj** [comment]
Hey @louislam take a look into this pr once free

File: .deepsource.toml [hunk 4]
```diff
@@ -0,0 +1,31 @@
+version = 1
```
Comment (CommanderStorm) [inline .deepsource.toml:1]: I don't see why we should add whatever this file is
Please remove this file

File: extra/healthcheck.go [hunk 5]
```diff
@@ -32,20 +32,20 @@ func main() {
 	}
 
 	sslKey := os.Getenv("UPTIME_KUMA_SSL_KEY")
-	if len(sslKey) == 0 {
+	if sslKey == "" {
```
Comment (CommanderStorm) [inline extra/healthcheck.go:35]: Entirely unrelated change.
Please revert this file

**Review by CommanderStorm — CHANGES_REQUESTED** [review]
Please remove the unrelated changes.
Otherwise this looks good to me

File: .deepsource.toml (hunk 4 above)
Comment (mohit-nagaraj) [reply .deepsource.toml]: sure sure it was my working changes tht got committed here sorry

File: extra/healthcheck.go (hunk 5 above)
Comment (mohit-nagaraj) [reply extra/healthcheck.go:35]: same thing with this as well will remove it

**Comment by mohit-nagaraj** [comment]
Done removed those changes

**Comment by mohit-nagaraj** [comment]
Hey @CommanderStorm can u review this when u get time 
Thank again

**Comment by mohit-nagaraj** [comment]
@CommanderStorm  could you review it when u get time

**Comment by mohit-nagaraj** [comment]
@CommanderStorm when is the earliest possible time u can retake a look in this again

**Review by CommanderStorm — APPROVED** [review]
Thanks for the work and the bugfix ❤️ 
Sorry for the long wait
