### PR TITLE
Fix: Show API Keys disabled msg. when disabled Auth

### LINKED ISSUE #4628: Disabling user auth also disables the API token requirement for /metrics
### 📑 I have found these related issues/pull requests

-/-

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have an API token to access /metrics which worked well. 

I have now disabled user authentication and added Authelia as a middleware, with both the /metrics and /api/push endpoints configured as 'bypass', with everything else requiring authentication.

To my surprise. the API token is no longer required anymore to access /metrics.

### 👟 Reproduction steps

see above

### 👀 Expected behavior

I expected that the /metrics endpoint still requires an API token. According to the docs, 

> By default, HTTP basic authentication is used to secure access to the Prometheus metrics endpoint. As soon as you add your first API key, the use of basic authentication for the endpoint will be permanently disabled.

### 😓 Actual Behavior

/metrics was unprotected

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

louislam/uptime-kuma:alpine (x64)

### 🌐 Browser

n/a

### 🖥️ Deployment Environment

n/a

### 📝 Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by chakflying**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

Fixes #4628

Show API Keys disabled message when Auth is disabled.

Small formatting change to existing code.

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- User interface (UI)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [ ] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

image

### CODE REVIEW

**Review by CommanderStorm — CHANGES_REQUESTED** [review]
Looks good. 👍🏻
Could you rebase this on 1.23.X?

**Review by CommanderStorm — APPROVED** [review]

File: src/components/settings/APIKeys.vue [hunk 1]
```diff
@@ -1,53 +1,63 @@
 <template>
     <div>
-        <div class="add-btn">
-            <button class="btn btn-primary me-2" type="button" @click="$refs.apiKeyDialog.show()">
-                <font-awesome-icon icon="plus" /> {{ $t("Add API Key") }}
-            </button>
+        <div
+            v-if="settings.disableAuth"
+            class="mt-5 d-flex align-items-center justify-content-center my-3"
```
Comment (CommanderStorm) [inline src/components/settings/APIKeys.vue:5]: The CI has not run on this branch.
I have no idea why, but I think addding another commit might fix it => lets test it

```suggestion
            class="mt-5 d-flex align-items-center justify-content-center my-3" 
```

File: src/components/settings/APIKeys.vue [hunk 2]
```diff
@@ -1,53 +1,63 @@
...
```
Comment (CommanderStorm) [inline src/components/settings/APIKeys.vue:5]: Revert of https://github.com/louislam/uptime-kuma/pull/4723#discussion_r1585464005

```suggestion
            class="mt-5 d-flex align-items-center justify-content-center my-3"
```
